# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_PostAccControl.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_PostAcc(object):
    def setupUi(self, MainWindow_PostAcc):
        MainWindow_PostAcc.setObjectName("MainWindow_PostAcc")
        MainWindow_PostAcc.resize(570, 147)
        self.centralwidget = QtWidgets.QWidget(MainWindow_PostAcc)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.pushButton_init_all = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_init_all.setObjectName("pushButton_init_all")
        self.gridLayout.addWidget(self.pushButton_init_all, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_name1 = QtWidgets.QLabel(self.centralwidget)
        self.label_name1.setObjectName("label_name1")
        self.gridLayout.addWidget(self.label_name1, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_name3 = QtWidgets.QLabel(self.centralwidget)
        self.label_name3.setObjectName("label_name3")
        self.gridLayout.addWidget(self.label_name3, 3, 0, 1, 1)
        self.label_name2 = QtWidgets.QLabel(self.centralwidget)
        self.label_name2.setObjectName("label_name2")
        self.gridLayout.addWidget(self.label_name2, 2, 0, 1, 1)
        self.label_con1 = QtWidgets.QLabel(self.centralwidget)
        self.label_con1.setObjectName("label_con1")
        self.gridLayout.addWidget(self.label_con1, 1, 1, 1, 1)
        self.label_con2 = QtWidgets.QLabel(self.centralwidget)
        self.label_con2.setObjectName("label_con2")
        self.gridLayout.addWidget(self.label_con2, 2, 1, 1, 1)
        self.doubleSpinBox_set_volt1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_set_volt1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_set_volt1.setKeyboardTracking(False)
        self.doubleSpinBox_set_volt1.setDecimals(1)
        self.doubleSpinBox_set_volt1.setMaximum(10000.0)
        self.doubleSpinBox_set_volt1.setObjectName("doubleSpinBox_set_volt1")
        self.gridLayout.addWidget(self.doubleSpinBox_set_volt1, 1, 2, 1, 1)
        self.label_con3 = QtWidgets.QLabel(self.centralwidget)
        self.label_con3.setObjectName("label_con3")
        self.gridLayout.addWidget(self.label_con3, 3, 1, 1, 1)
        self.label_last_set3 = QtWidgets.QLabel(self.centralwidget)
        self.label_last_set3.setObjectName("label_last_set3")
        self.gridLayout.addWidget(self.label_last_set3, 3, 4, 1, 1)
        self.doubleSpinBox_set_volt3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_set_volt3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_set_volt3.setKeyboardTracking(False)
        self.doubleSpinBox_set_volt3.setDecimals(1)
        self.doubleSpinBox_set_volt3.setMaximum(10000.0)
        self.doubleSpinBox_set_volt3.setObjectName("doubleSpinBox_set_volt3")
        self.gridLayout.addWidget(self.doubleSpinBox_set_volt3, 3, 2, 1, 1)
        self.label_last_set1 = QtWidgets.QLabel(self.centralwidget)
        self.label_last_set1.setMinimumSize(QtCore.QSize(80, 0))
        self.label_last_set1.setObjectName("label_last_set1")
        self.gridLayout.addWidget(self.label_last_set1, 1, 4, 1, 1)
        self.doubleSpinBox_set_volt2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_set_volt2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_set_volt2.setKeyboardTracking(False)
        self.doubleSpinBox_set_volt2.setDecimals(1)
        self.doubleSpinBox_set_volt2.setMaximum(10000.0)
        self.doubleSpinBox_set_volt2.setObjectName("doubleSpinBox_set_volt2")
        self.gridLayout.addWidget(self.doubleSpinBox_set_volt2, 2, 2, 1, 1)
        self.label_last_set2 = QtWidgets.QLabel(self.centralwidget)
        self.label_last_set2.setObjectName("label_last_set2")
        self.gridLayout.addWidget(self.label_last_set2, 2, 4, 1, 1)
        self.pushButton_on_off1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_on_off1.setObjectName("pushButton_on_off1")
        self.gridLayout.addWidget(self.pushButton_on_off1, 1, 6, 1, 1)
        self.label_volt_read2 = QtWidgets.QLabel(self.centralwidget)
        self.label_volt_read2.setObjectName("label_volt_read2")
        self.gridLayout.addWidget(self.label_volt_read2, 2, 5, 1, 1)
        self.label_volt_read1 = QtWidgets.QLabel(self.centralwidget)
        self.label_volt_read1.setObjectName("label_volt_read1")
        self.gridLayout.addWidget(self.label_volt_read1, 1, 5, 1, 1)
        self.label_volt_read3 = QtWidgets.QLabel(self.centralwidget)
        self.label_volt_read3.setObjectName("label_volt_read3")
        self.gridLayout.addWidget(self.label_volt_read3, 3, 5, 1, 1)
        self.pushButton_on_off2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_on_off2.setObjectName("pushButton_on_off2")
        self.gridLayout.addWidget(self.pushButton_on_off2, 2, 6, 1, 1)
        self.pushButton_on_off3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_on_off3.setObjectName("pushButton_on_off3")
        self.gridLayout.addWidget(self.pushButton_on_off3, 3, 6, 1, 1)
        self.pushButton_all_on_off = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_all_on_off.setObjectName("pushButton_all_on_off")
        self.gridLayout.addWidget(self.pushButton_all_on_off, 4, 6, 1, 1)
        self.pushButton_set_volt1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_volt1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_set_volt1.sizePolicy().hasHeightForWidth())
        self.pushButton_set_volt1.setSizePolicy(sizePolicy)
        self.pushButton_set_volt1.setMinimumSize(QtCore.QSize(10, 23))
        self.pushButton_set_volt1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_set_volt1.setBaseSize(QtCore.QSize(1, 0))
        self.pushButton_set_volt1.setObjectName("pushButton_set_volt1")
        self.gridLayout.addWidget(self.pushButton_set_volt1, 1, 3, 1, 1)
        self.pushButton_set_volt2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_volt2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_set_volt2.sizePolicy().hasHeightForWidth())
        self.pushButton_set_volt2.setSizePolicy(sizePolicy)
        self.pushButton_set_volt2.setMinimumSize(QtCore.QSize(10, 23))
        self.pushButton_set_volt2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_set_volt2.setBaseSize(QtCore.QSize(1, 0))
        self.pushButton_set_volt2.setObjectName("pushButton_set_volt2")
        self.gridLayout.addWidget(self.pushButton_set_volt2, 2, 3, 1, 1)
        self.pushButton_set_volt3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_volt3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_set_volt3.sizePolicy().hasHeightForWidth())
        self.pushButton_set_volt3.setSizePolicy(sizePolicy)
        self.pushButton_set_volt3.setMinimumSize(QtCore.QSize(10, 23))
        self.pushButton_set_volt3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_set_volt3.setBaseSize(QtCore.QSize(1, 0))
        self.pushButton_set_volt3.setObjectName("pushButton_set_volt3")
        self.gridLayout.addWidget(self.pushButton_set_volt3, 3, 3, 1, 1)
        self.pushButton_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.gridLayout.addWidget(self.pushButton_refresh, 4, 5, 1, 1)
        MainWindow_PostAcc.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_PostAcc)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_PostAcc)
        MainWindow_PostAcc.setTabOrder(self.doubleSpinBox_set_volt1, self.pushButton_set_volt1)
        MainWindow_PostAcc.setTabOrder(self.pushButton_set_volt1, self.pushButton_on_off1)
        MainWindow_PostAcc.setTabOrder(self.pushButton_on_off1, self.doubleSpinBox_set_volt2)
        MainWindow_PostAcc.setTabOrder(self.doubleSpinBox_set_volt2, self.pushButton_set_volt2)
        MainWindow_PostAcc.setTabOrder(self.pushButton_set_volt2, self.pushButton_on_off2)
        MainWindow_PostAcc.setTabOrder(self.pushButton_on_off2, self.doubleSpinBox_set_volt3)
        MainWindow_PostAcc.setTabOrder(self.doubleSpinBox_set_volt3, self.pushButton_set_volt3)
        MainWindow_PostAcc.setTabOrder(self.pushButton_set_volt3, self.pushButton_on_off3)
        MainWindow_PostAcc.setTabOrder(self.pushButton_on_off3, self.pushButton_init_all)
        MainWindow_PostAcc.setTabOrder(self.pushButton_init_all, self.pushButton_refresh)
        MainWindow_PostAcc.setTabOrder(self.pushButton_refresh, self.pushButton_all_on_off)

    def retranslateUi(self, MainWindow_PostAcc):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_PostAcc.setWindowTitle(_translate("MainWindow_PostAcc", "Post acceleration power supplies"))
        self.label_4.setText(_translate("MainWindow_PostAcc", "voltage readback"))
        self.label.setText(_translate("MainWindow_PostAcc", "devName"))
        self.label_2.setText(_translate("MainWindow_PostAcc", "connection"))
        self.pushButton_init_all.setText(_translate("MainWindow_PostAcc", "reinitialize all"))
        self.label_3.setText(_translate("MainWindow_PostAcc", "set voltage"))
        self.label_name1.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_5.setText(_translate("MainWindow_PostAcc", "output on/off"))
        self.label_6.setText(_translate("MainWindow_PostAcc", "last set"))
        self.label_name3.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_name2.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_con1.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_con2.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_con3.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_last_set3.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_last_set1.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_last_set2.setText(_translate("MainWindow_PostAcc", "None"))
        self.pushButton_on_off1.setText(_translate("MainWindow_PostAcc", "on/off"))
        self.label_volt_read2.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_volt_read1.setText(_translate("MainWindow_PostAcc", "None"))
        self.label_volt_read3.setText(_translate("MainWindow_PostAcc", "None"))
        self.pushButton_on_off2.setText(_translate("MainWindow_PostAcc", "on/off"))
        self.pushButton_on_off3.setText(_translate("MainWindow_PostAcc", "on/off"))
        self.pushButton_all_on_off.setText(_translate("MainWindow_PostAcc", "all output off"))
        self.pushButton_set_volt1.setText(_translate("MainWindow_PostAcc", "set1"))
        self.pushButton_set_volt2.setText(_translate("MainWindow_PostAcc", "set2"))
        self.pushButton_set_volt3.setText(_translate("MainWindow_PostAcc", "set3"))
        self.pushButton_refresh.setText(_translate("MainWindow_PostAcc", "refresh"))

