# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ScanProgress.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScanProgress(object):
    def setupUi(self, ScanProgress):
        ScanProgress.setObjectName("ScanProgress")
        ScanProgress.resize(194, 293)
        self.centralwidget = QtWidgets.QWidget(ScanProgress)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_timeleft_set = QtWidgets.QLabel(self.groupBox_2)
        self.label_timeleft_set.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_timeleft_set.setObjectName("label_timeleft_set")
        self.gridLayout_4.addWidget(self.label_timeleft_set, 1, 1, 1, 1)
        self.label_timeleft = QtWidgets.QLabel(self.groupBox_2)
        self.label_timeleft.setObjectName("label_timeleft")
        self.gridLayout_4.addWidget(self.label_timeleft, 1, 0, 1, 1)
        self.progressBar_overall = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_overall.setProperty("value", 24)
        self.progressBar_overall.setObjectName("progressBar_overall")
        self.gridLayout_4.addWidget(self.progressBar_overall, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_act_track_num = QtWidgets.QLabel(self.groupBox_2)
        self.label_act_track_num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_act_track_num.setObjectName("label_act_track_num")
        self.gridLayout_3.addWidget(self.label_act_track_num, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_total_track_num = QtWidgets.QLabel(self.groupBox_2)
        self.label_total_track_num.setObjectName("label_total_track_num")
        self.gridLayout_3.addWidget(self.label_total_track_num, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.progressBar_track = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_track.setProperty("value", 24)
        self.progressBar_track.setTextVisible(True)
        self.progressBar_track.setObjectName("progressBar_track")
        self.gridLayout_5.addWidget(self.progressBar_track, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_max_scan_number = QtWidgets.QLabel(self.groupBox)
        self.label_max_scan_number.setObjectName("label_max_scan_number")
        self.gridLayout.addWidget(self.label_max_scan_number, 1, 3, 1, 1)
        self.label_act_completed_steps = QtWidgets.QLabel(self.groupBox)
        self.label_act_completed_steps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_act_completed_steps.setObjectName("label_act_completed_steps")
        self.gridLayout.addWidget(self.label_act_completed_steps, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_max_completed_steps = QtWidgets.QLabel(self.groupBox)
        self.label_max_completed_steps.setObjectName("label_max_completed_steps")
        self.gridLayout.addWidget(self.label_max_completed_steps, 2, 3, 1, 1)
        self.label_completedSteps = QtWidgets.QLabel(self.groupBox)
        self.label_completedSteps.setObjectName("label_completedSteps")
        self.gridLayout.addWidget(self.label_completedSteps, 2, 0, 1, 1)
        self.label_act_scan_number = QtWidgets.QLabel(self.groupBox)
        self.label_act_scan_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_act_scan_number.setObjectName("label_act_scan_number")
        self.gridLayout.addWidget(self.label_act_scan_number, 1, 1, 1, 1)
        self.label_scanNumber = QtWidgets.QLabel(self.groupBox)
        self.label_scanNumber.setObjectName("label_scanNumber")
        self.gridLayout.addWidget(self.label_scanNumber, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_halt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_halt.setObjectName("pushButton_halt")
        self.gridLayout_2.addWidget(self.pushButton_halt, 1, 0, 1, 1)
        self.pushButton_abort = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.gridLayout_2.addWidget(self.pushButton_abort, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        ScanProgress.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ScanProgress)
        self.statusbar.setObjectName("statusbar")
        ScanProgress.setStatusBar(self.statusbar)

        self.retranslateUi(ScanProgress)
        QtCore.QMetaObject.connectSlotsByName(ScanProgress)

    def retranslateUi(self, ScanProgress):
        _translate = QtCore.QCoreApplication.translate
        ScanProgress.setWindowTitle(_translate("ScanProgress", "ScanProgress"))
        self.groupBox_2.setTitle(_translate("ScanProgress", "overall"))
        self.label_timeleft_set.setText(_translate("ScanProgress", "0"))
        self.label_timeleft.setText(_translate("ScanProgress", "timeleft:"))
        self.label_3.setText(_translate("ScanProgress", "track:"))
        self.label_act_track_num.setText(_translate("ScanProgress", "0"))
        self.label_5.setText(_translate("ScanProgress", "of"))
        self.label_total_track_num.setText(_translate("ScanProgress", "0"))
        self.groupBox.setTitle(_translate("ScanProgress", "track"))
        self.label_max_scan_number.setText(_translate("ScanProgress", "0"))
        self.label_act_completed_steps.setText(_translate("ScanProgress", "0"))
        self.label_8.setText(_translate("ScanProgress", "of"))
        self.label_7.setText(_translate("ScanProgress", "of"))
        self.label_max_completed_steps.setText(_translate("ScanProgress", "0"))
        self.label_completedSteps.setText(_translate("ScanProgress", "completed\n"
"steps:"))
        self.label_act_scan_number.setText(_translate("ScanProgress", "0"))
        self.label_scanNumber.setText(_translate("ScanProgress", "scan\n"
"number:"))
        self.pushButton_halt.setText(_translate("ScanProgress", "Halt"))
        self.pushButton_abort.setText(_translate("ScanProgress", "Abort"))

