# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ScanProgress.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(204, 173)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_scanNumber = QtWidgets.QLabel(self.centralwidget)
        self.label_scanNumber.setObjectName("label_scanNumber")
        self.gridLayout.addWidget(self.label_scanNumber, 0, 0, 1, 1)
        self.label_act_scanNumber = QtWidgets.QLabel(self.centralwidget)
        self.label_act_scanNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_act_scanNumber.setObjectName("label_act_scanNumber")
        self.gridLayout.addWidget(self.label_act_scanNumber, 0, 1, 1, 1)
        self.label_completedSteps = QtWidgets.QLabel(self.centralwidget)
        self.label_completedSteps.setObjectName("label_completedSteps")
        self.gridLayout.addWidget(self.label_completedSteps, 1, 0, 1, 1)
        self.label_act_completedSteps = QtWidgets.QLabel(self.centralwidget)
        self.label_act_completedSteps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_act_completedSteps.setObjectName("label_act_completedSteps")
        self.gridLayout.addWidget(self.label_act_completedSteps, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_max_scanNumber = QtWidgets.QLabel(self.centralwidget)
        self.label_max_scanNumber.setObjectName("label_max_scanNumber")
        self.gridLayout.addWidget(self.label_max_scanNumber, 0, 3, 1, 1)
        self.label_max_completedSteps = QtWidgets.QLabel(self.centralwidget)
        self.label_max_completedSteps.setObjectName("label_max_completedSteps")
        self.gridLayout.addWidget(self.label_max_completedSteps, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_timeleft_set = QtWidgets.QLabel(self.centralwidget)
        self.label_timeleft_set.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_timeleft_set.setObjectName("label_timeleft_set")
        self.gridLayout_2.addWidget(self.label_timeleft_set, 0, 1, 1, 1)
        self.label_timeleft = QtWidgets.QLabel(self.centralwidget)
        self.label_timeleft.setObjectName("label_timeleft")
        self.gridLayout_2.addWidget(self.label_timeleft, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_scanNumber.setText(_translate("MainWindow", "scan number:"))
        self.label_act_scanNumber.setText(_translate("MainWindow", "0"))
        self.label_completedSteps.setText(_translate("MainWindow", "compeleted steps:"))
        self.label_act_completedSteps.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "of"))
        self.label_7.setText(_translate("MainWindow", "of"))
        self.label_max_scanNumber.setText(_translate("MainWindow", "0"))
        self.label_max_completedSteps.setText(_translate("MainWindow", "0"))
        self.label_timeleft_set.setText(_translate("MainWindow", "0"))
        self.label_timeleft.setText(_translate("MainWindow", "timeleft:"))
        self.pushButton.setText(_translate("MainWindow", "Halt"))
        self.pushButton_2.setText(_translate("MainWindow", "Abort"))

