# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ColAcol.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ColAcol(object):
    def setupUi(self, ColAcol):
        ColAcol.setObjectName("ColAcol")
        ColAcol.setWindowModality(QtCore.Qt.NonModal)
        ColAcol.resize(744, 446)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(ColAcol)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.oAll = QtWidgets.QLabel(ColAcol)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oAll.setFont(font)
        self.oAll.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.oAll.setAlignment(QtCore.Qt.AlignCenter)
        self.oAll.setObjectName("oAll")
        self.verticalLayout.addWidget(self.oAll)
        self.lAll = QtWidgets.QListWidget(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lAll.sizePolicy().hasHeightForWidth())
        self.lAll.setSizePolicy(sizePolicy)
        self.lAll.setMinimumSize(QtCore.QSize(185, 300))
        self.lAll.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lAll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lAll.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.lAll.setObjectName("lAll")
        self.verticalLayout.addWidget(self.lAll)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(ColAcol)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.oCol = QtWidgets.QLabel(ColAcol)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oCol.setFont(font)
        self.oCol.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.oCol.setAlignment(QtCore.Qt.AlignCenter)
        self.oCol.setObjectName("oCol")
        self.verticalLayout_2.addWidget(self.oCol)
        self.lCol = QtWidgets.QListWidget(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lCol.sizePolicy().hasHeightForWidth())
        self.lCol.setSizePolicy(sizePolicy)
        self.lCol.setMinimumSize(QtCore.QSize(185, 300))
        self.lCol.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lCol.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.lCol.setObjectName("lCol")
        self.verticalLayout_2.addWidget(self.lCol)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.oArrow = QtWidgets.QLabel(ColAcol)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.oArrow.setFont(font)
        self.oArrow.setObjectName("oArrow")
        self.horizontalLayout.addWidget(self.oArrow)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.oAcol = QtWidgets.QLabel(ColAcol)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oAcol.setFont(font)
        self.oAcol.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.oAcol.setAlignment(QtCore.Qt.AlignCenter)
        self.oAcol.setObjectName("oAcol")
        self.verticalLayout_3.addWidget(self.oAcol)
        self.lAcol = QtWidgets.QListWidget(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lAcol.sizePolicy().hasHeightForWidth())
        self.lAcol.setSizePolicy(sizePolicy)
        self.lAcol.setMinimumSize(QtCore.QSize(185, 300))
        self.lAcol.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lAcol.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.lAcol.setObjectName("lAcol")
        self.verticalLayout_3.addWidget(self.lAcol)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bCol = QtWidgets.QPushButton(ColAcol)
        self.bCol.setMinimumSize(QtCore.QSize(185, 25))
        self.bCol.setMaximumSize(QtCore.QSize(185, 25))
        self.bCol.setObjectName("bCol")
        self.horizontalLayout_2.addWidget(self.bCol)
        self.line_2 = QtWidgets.QFrame(ColAcol)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.oFile = QtWidgets.QLabel(ColAcol)
        self.oFile.setMinimumSize(QtCore.QSize(70, 25))
        self.oFile.setMaximumSize(QtCore.QSize(16777215, 25))
        self.oFile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oFile.setObjectName("oFile")
        self.horizontalLayout_2.addWidget(self.oFile)
        self.iFile = QtWidgets.QLineEdit(ColAcol)
        self.iFile.setMinimumSize(QtCore.QSize(350, 25))
        self.iFile.setMaximumSize(QtCore.QSize(350, 25))
        self.iFile.setObjectName("iFile")
        self.horizontalLayout_2.addWidget(self.iFile)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bAcol = QtWidgets.QPushButton(ColAcol)
        self.bAcol.setMinimumSize(QtCore.QSize(185, 25))
        self.bAcol.setMaximumSize(QtCore.QSize(185, 25))
        self.bAcol.setObjectName("bAcol")
        self.horizontalLayout_3.addWidget(self.bAcol)
        self.line_3 = QtWidgets.QFrame(ColAcol)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.oPath = QtWidgets.QLabel(ColAcol)
        self.oPath.setMinimumSize(QtCore.QSize(70, 25))
        self.oPath.setMaximumSize(QtCore.QSize(20000, 25))
        self.oPath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oPath.setObjectName("oPath")
        self.horizontalLayout_3.addWidget(self.oPath)
        self.iPath = QtWidgets.QLineEdit(ColAcol)
        self.iPath.setMinimumSize(QtCore.QSize(350, 25))
        self.iPath.setMaximumSize(QtCore.QSize(350, 25))
        self.iPath.setObjectName("iPath")
        self.horizontalLayout_3.addWidget(self.iPath)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bReset = QtWidgets.QPushButton(ColAcol)
        self.bReset.setMinimumSize(QtCore.QSize(185, 25))
        self.bReset.setMaximumSize(QtCore.QSize(185, 25))
        self.bReset.setObjectName("bReset")
        self.horizontalLayout_4.addWidget(self.bReset)
        self.line_4 = QtWidgets.QFrame(ColAcol)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.bStart = QtWidgets.QPushButton(ColAcol)
        self.bStart.setMinimumSize(QtCore.QSize(350, 25))
        self.bStart.setMaximumSize(QtCore.QSize(350, 25))
        self.bStart.setObjectName("bStart")
        self.horizontalLayout_4.addWidget(self.bStart)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.oAll.raise_()

        self.retranslateUi(ColAcol)
        QtCore.QMetaObject.connectSlotsByName(ColAcol)

    def retranslateUi(self, ColAcol):
        _translate = QtCore.QCoreApplication.translate
        ColAcol.setWindowTitle(_translate("ColAcol", "Form"))
        self.oAll.setText(_translate("ColAcol", "All Fitted Spectra"))
        self.oCol.setText(_translate("ColAcol", "Collinear Spectra"))
        self.oArrow.setText(_translate("ColAcol", "↔"))
        self.oAcol.setText(_translate("ColAcol", "Anti-collinear Spectra"))
        self.bCol.setText(_translate("ColAcol", "Collinear ->"))
        self.oFile.setText(_translate("ColAcol", "File Name"))
        self.bAcol.setText(_translate("ColAcol", "Anti-Collinear ->"))
        self.oPath.setText(_translate("ColAcol", "Output Path"))
        self.bReset.setText(_translate("ColAcol", "<- Reset"))
        self.bStart.setText(_translate("ColAcol", "Start!"))

