# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Users\Patrick\Documents\Python Projects\Tilda\PolliFit\source\Gui\Ui_HFMixingConfig.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HFMixingConfig(object):
    def setupUi(self, HFMixingConfig):
        HFMixingConfig.setObjectName("HFMixingConfig")
        HFMixingConfig.resize(900, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HFMixingConfig.sizePolicy().hasHeightForWidth())
        HFMixingConfig.setSizePolicy(sizePolicy)
        HFMixingConfig.setMinimumSize(QtCore.QSize(0, 200))
        HFMixingConfig.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Europe))
        self.verticalLayout = QtWidgets.QVBoxLayout(HFMixingConfig)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_info = QtWidgets.QLabel(HFMixingConfig)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_info.setFont(font)
        self.l_info.setObjectName("l_info")
        self.verticalLayout.addWidget(self.l_info)
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.hline_top = QtWidgets.QFrame(HFMixingConfig)
        self.hline_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline_top.setObjectName("hline_top")
        self.verticalLayout.addWidget(self.hline_top)
        self.hor_g = QtWidgets.QHBoxLayout()
        self.hor_g.setObjectName("hor_g")
        self.l_g = QtWidgets.QLabel(HFMixingConfig)
        self.l_g.setObjectName("l_g")
        self.hor_g.addWidget(self.l_g)
        self.d_g = QtWidgets.QDoubleSpinBox(HFMixingConfig)
        self.d_g.setReadOnly(True)
        self.d_g.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.d_g.setDecimals(1)
        self.d_g.setSingleStep(0.5)
        self.d_g.setProperty("value", 0.5)
        self.d_g.setObjectName("d_g")
        self.hor_g.addWidget(self.d_g)
        self.check_g = QtWidgets.QCheckBox(HFMixingConfig)
        self.check_g.setChecked(False)
        self.check_g.setObjectName("check_g")
        self.hor_g.addWidget(self.check_g)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_g.addItem(spacerItem1)
        self.line_info_g = QtWidgets.QLineEdit(HFMixingConfig)
        self.line_info_g.setReadOnly(True)
        self.line_info_g.setObjectName("line_info_g")
        self.hor_g.addWidget(self.line_info_g)
        self.verticalLayout.addLayout(self.hor_g)
        self.hor_widget_g = QtWidgets.QWidget(HFMixingConfig)
        self.hor_widget_g.setEnabled(False)
        self.hor_widget_g.setObjectName("hor_widget_g")
        self.hor_config_g = QtWidgets.QHBoxLayout(self.hor_widget_g)
        self.hor_config_g.setContentsMargins(0, -1, 0, -1)
        self.hor_config_g.setObjectName("hor_config_g")
        self.ver_qn_setup_g = QtWidgets.QVBoxLayout()
        self.ver_qn_setup_g.setObjectName("ver_qn_setup_g")
        self.hor_j_g = QtWidgets.QHBoxLayout()
        self.hor_j_g.setObjectName("hor_j_g")
        self.l_j_g = QtWidgets.QLabel(self.hor_widget_g)
        self.l_j_g.setObjectName("l_j_g")
        self.hor_j_g.addWidget(self.l_j_g)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_j_g.addItem(spacerItem2)
        self.b_help_g = QtWidgets.QPushButton(self.hor_widget_g)
        self.b_help_g.setMaximumSize(QtCore.QSize(40, 16777215))
        self.b_help_g.setObjectName("b_help_g")
        self.hor_j_g.addWidget(self.b_help_g)
        self.ver_qn_setup_g.addLayout(self.hor_j_g)
        self.line_j_g = QtWidgets.QLineEdit(self.hor_widget_g)
        self.line_j_g.setObjectName("line_j_g")
        self.ver_qn_setup_g.addWidget(self.line_j_g)
        self.label = QtWidgets.QLabel(self.hor_widget_g)
        self.label.setObjectName("label")
        self.ver_qn_setup_g.addWidget(self.label)
        self.grid_presets_g = QtWidgets.QGridLayout()
        self.grid_presets_g.setObjectName("grid_presets_g")
        self.b_diagonal_g = QtWidgets.QPushButton(self.hor_widget_g)
        self.b_diagonal_g.setObjectName("b_diagonal_g")
        self.grid_presets_g.addWidget(self.b_diagonal_g, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.hor_widget_g)
        self.pushButton.setObjectName("pushButton")
        self.grid_presets_g.addWidget(self.pushButton, 0, 1, 1, 1)
        self.ver_qn_setup_g.addLayout(self.grid_presets_g)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ver_qn_setup_g.addItem(spacerItem3)
        self.hor_buttons_g = QtWidgets.QHBoxLayout()
        self.hor_buttons_g.setObjectName("hor_buttons_g")
        self.b_apply_g = QtWidgets.QPushButton(self.hor_widget_g)
        self.b_apply_g.setObjectName("b_apply_g")
        self.hor_buttons_g.addWidget(self.b_apply_g)
        self.b_reset_g = QtWidgets.QPushButton(self.hor_widget_g)
        self.b_reset_g.setObjectName("b_reset_g")
        self.hor_buttons_g.addWidget(self.b_reset_g)
        self.ver_qn_setup_g.addLayout(self.hor_buttons_g)
        self.hor_config_g.addLayout(self.ver_qn_setup_g)
        self.tab_g = QtWidgets.QTableWidget(self.hor_widget_g)
        self.tab_g.setObjectName("tab_g")
        self.tab_g.setColumnCount(1)
        self.tab_g.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tab_g.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_g.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_g.setItem(0, 0, item)
        self.hor_config_g.addWidget(self.tab_g)
        self.hor_config_g.setStretch(1, 1)
        self.verticalLayout.addWidget(self.hor_widget_g)
        self.hline_g = QtWidgets.QFrame(HFMixingConfig)
        self.hline_g.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline_g.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline_g.setObjectName("hline_g")
        self.verticalLayout.addWidget(self.hline_g)
        spacerItem4 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.hor_e = QtWidgets.QHBoxLayout()
        self.hor_e.setObjectName("hor_e")
        self.l_e = QtWidgets.QLabel(HFMixingConfig)
        self.l_e.setObjectName("l_e")
        self.hor_e.addWidget(self.l_e)
        self.d_e = QtWidgets.QDoubleSpinBox(HFMixingConfig)
        self.d_e.setReadOnly(True)
        self.d_e.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.d_e.setDecimals(1)
        self.d_e.setSingleStep(0.5)
        self.d_e.setProperty("value", 0.5)
        self.d_e.setObjectName("d_e")
        self.hor_e.addWidget(self.d_e)
        self.check_e = QtWidgets.QCheckBox(HFMixingConfig)
        self.check_e.setObjectName("check_e")
        self.hor_e.addWidget(self.check_e)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_e.addItem(spacerItem5)
        self.line_info_e = QtWidgets.QLineEdit(HFMixingConfig)
        self.line_info_e.setReadOnly(True)
        self.line_info_e.setObjectName("line_info_e")
        self.hor_e.addWidget(self.line_info_e)
        self.verticalLayout.addLayout(self.hor_e)
        self.hor_widget_e = QtWidgets.QWidget(HFMixingConfig)
        self.hor_widget_e.setEnabled(False)
        self.hor_widget_e.setObjectName("hor_widget_e")
        self.hor_config_e = QtWidgets.QHBoxLayout(self.hor_widget_e)
        self.hor_config_e.setContentsMargins(0, -1, 0, -1)
        self.hor_config_e.setObjectName("hor_config_e")
        self.ver_qn_setup_e = QtWidgets.QVBoxLayout()
        self.ver_qn_setup_e.setObjectName("ver_qn_setup_e")
        self.hor_j_e = QtWidgets.QHBoxLayout()
        self.hor_j_e.setObjectName("hor_j_e")
        self.l_j_e = QtWidgets.QLabel(self.hor_widget_e)
        self.l_j_e.setObjectName("l_j_e")
        self.hor_j_e.addWidget(self.l_j_e)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_j_e.addItem(spacerItem6)
        self.b_help_e = QtWidgets.QPushButton(self.hor_widget_e)
        self.b_help_e.setMaximumSize(QtCore.QSize(40, 16777215))
        self.b_help_e.setObjectName("b_help_e")
        self.hor_j_e.addWidget(self.b_help_e)
        self.ver_qn_setup_e.addLayout(self.hor_j_e)
        self.line_j_e = QtWidgets.QLineEdit(self.hor_widget_e)
        self.line_j_e.setObjectName("line_j_e")
        self.ver_qn_setup_e.addWidget(self.line_j_e)
        self.label_2 = QtWidgets.QLabel(self.hor_widget_e)
        self.label_2.setObjectName("label_2")
        self.ver_qn_setup_e.addWidget(self.label_2)
        self.grid_presets_e = QtWidgets.QGridLayout()
        self.grid_presets_e.setObjectName("grid_presets_e")
        self.b_diagonal_e = QtWidgets.QPushButton(self.hor_widget_e)
        self.b_diagonal_e.setObjectName("b_diagonal_e")
        self.grid_presets_e.addWidget(self.b_diagonal_e, 0, 0, 1, 1)
        self.b_nomixing_e = QtWidgets.QPushButton(self.hor_widget_e)
        self.b_nomixing_e.setObjectName("b_nomixing_e")
        self.grid_presets_e.addWidget(self.b_nomixing_e, 0, 1, 1, 1)
        self.ver_qn_setup_e.addLayout(self.grid_presets_e)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ver_qn_setup_e.addItem(spacerItem7)
        self.hor_buttons_e = QtWidgets.QHBoxLayout()
        self.hor_buttons_e.setObjectName("hor_buttons_e")
        self.b_apply_e = QtWidgets.QPushButton(self.hor_widget_e)
        self.b_apply_e.setObjectName("b_apply_e")
        self.hor_buttons_e.addWidget(self.b_apply_e)
        self.b_reset_e = QtWidgets.QPushButton(self.hor_widget_e)
        self.b_reset_e.setObjectName("b_reset_e")
        self.hor_buttons_e.addWidget(self.b_reset_e)
        self.ver_qn_setup_e.addLayout(self.hor_buttons_e)
        self.hor_config_e.addLayout(self.ver_qn_setup_e)
        self.tab_e = QtWidgets.QTableWidget(self.hor_widget_e)
        self.tab_e.setObjectName("tab_e")
        self.tab_e.setColumnCount(1)
        self.tab_e.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tab_e.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_e.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_e.setItem(0, 0, item)
        self.hor_config_e.addWidget(self.tab_e)
        self.hor_config_e.setStretch(1, 1)
        self.verticalLayout.addWidget(self.hor_widget_e)
        self.hline_e = QtWidgets.QFrame(HFMixingConfig)
        self.hline_e.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline_e.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline_e.setObjectName("hline_e")
        self.verticalLayout.addWidget(self.hline_e)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.hor_buttons = QtWidgets.QHBoxLayout()
        self.hor_buttons.setObjectName("hor_buttons")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_buttons.addItem(spacerItem9)
        self.b_ok = QtWidgets.QPushButton(HFMixingConfig)
        self.b_ok.setObjectName("b_ok")
        self.hor_buttons.addWidget(self.b_ok)
        self.b_apply = QtWidgets.QPushButton(HFMixingConfig)
        self.b_apply.setObjectName("b_apply")
        self.hor_buttons.addWidget(self.b_apply)
        self.b_reset = QtWidgets.QPushButton(HFMixingConfig)
        self.b_reset.setObjectName("b_reset")
        self.hor_buttons.addWidget(self.b_reset)
        self.b_cancel = QtWidgets.QPushButton(HFMixingConfig)
        self.b_cancel.setObjectName("b_cancel")
        self.hor_buttons.addWidget(self.b_cancel)
        self.verticalLayout.addLayout(self.hor_buttons)

        self.retranslateUi(HFMixingConfig)
        QtCore.QMetaObject.connectSlotsByName(HFMixingConfig)

    def retranslateUi(self, HFMixingConfig):
        _translate = QtCore.QCoreApplication.translate
        HFMixingConfig.setWindowTitle(_translate("HFMixingConfig", "Hyperfine Mixing Configuration"))
        self.l_info.setText(_translate("HFMixingConfig", "Hyperfine Mixing Configuration"))
        self.l_g.setText(_translate("HFMixingConfig", "Lower state J"))
        self.check_g.setText(_translate("HFMixingConfig", "enabled"))
        self.l_j_g.setText(_translate("HFMixingConfig", "mixed J\'s:"))
        self.b_help_g.setText(_translate("HFMixingConfig", "?"))
        self.line_j_g.setText(_translate("HFMixingConfig", "[0.5]"))
        self.label.setText(_translate("HFMixingConfig", "presets:"))
        self.b_diagonal_g.setText(_translate("HFMixingConfig", "diagonal"))
        self.pushButton.setText(_translate("HFMixingConfig", "no mixing"))
        self.b_apply_g.setText(_translate("HFMixingConfig", "apply"))
        self.b_reset_g.setText(_translate("HFMixingConfig", "reset"))
        item = self.tab_g.verticalHeaderItem(0)
        item.setText(_translate("HFMixingConfig", "0"))
        item = self.tab_g.horizontalHeaderItem(0)
        item.setText(_translate("HFMixingConfig", "0"))
        __sortingEnabled = self.tab_g.isSortingEnabled()
        self.tab_g.setSortingEnabled(False)
        item = self.tab_g.item(0, 0)
        item.setText(_translate("HFMixingConfig", "1"))
        self.tab_g.setSortingEnabled(__sortingEnabled)
        self.l_e.setText(_translate("HFMixingConfig", "Upper state J"))
        self.check_e.setText(_translate("HFMixingConfig", "enabled"))
        self.l_j_e.setText(_translate("HFMixingConfig", "mixed J\'s:"))
        self.b_help_e.setText(_translate("HFMixingConfig", "?"))
        self.line_j_e.setText(_translate("HFMixingConfig", "[0.5]"))
        self.label_2.setText(_translate("HFMixingConfig", "presets:"))
        self.b_diagonal_e.setText(_translate("HFMixingConfig", "diagonal"))
        self.b_nomixing_e.setText(_translate("HFMixingConfig", "no mixing"))
        self.b_apply_e.setText(_translate("HFMixingConfig", "apply"))
        self.b_reset_e.setText(_translate("HFMixingConfig", "reset"))
        item = self.tab_e.verticalHeaderItem(0)
        item.setText(_translate("HFMixingConfig", "0"))
        item = self.tab_e.horizontalHeaderItem(0)
        item.setText(_translate("HFMixingConfig", "0"))
        __sortingEnabled = self.tab_e.isSortingEnabled()
        self.tab_e.setSortingEnabled(False)
        item = self.tab_e.item(0, 0)
        item.setText(_translate("HFMixingConfig", "1"))
        self.tab_e.setSortingEnabled(__sortingEnabled)
        self.b_ok.setText(_translate("HFMixingConfig", "OK"))
        self.b_apply.setText(_translate("HFMixingConfig", "apply"))
        self.b_reset.setText(_translate("HFMixingConfig", "reset"))
        self.b_cancel.setText(_translate("HFMixingConfig", "Cancel"))
