# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_InteractiveFit.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InteractiveFit(object):
    def setupUi(self, InteractiveFit):
        InteractiveFit.setObjectName("InteractiveFit")
        InteractiveFit.resize(381, 330)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(InteractiveFit)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.runSelect = QtWidgets.QComboBox(InteractiveFit)
        self.runSelect.setObjectName("runSelect")
        self.verticalLayout.addWidget(self.runSelect)
        self.isoFilter = QtWidgets.QComboBox(InteractiveFit)
        self.isoFilter.setObjectName("isoFilter")
        self.verticalLayout.addWidget(self.isoFilter)
        self.fileList = QtWidgets.QListWidget(InteractiveFit)
        self.fileList.setObjectName("fileList")
        self.verticalLayout.addWidget(self.fileList)
        self.bLoad = QtWidgets.QPushButton(InteractiveFit)
        self.bLoad.setObjectName("bLoad")
        self.verticalLayout.addWidget(self.bLoad)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.parTable = QtWidgets.QTableWidget(InteractiveFit)
        self.parTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.parTable.setColumnCount(3)
        self.parTable.setObjectName("parTable")
        self.parTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.parTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.parTable.setHorizontalHeaderItem(2, item)
        self.parTable.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.parTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bFit = QtWidgets.QPushButton(InteractiveFit)
        self.bFit.setObjectName("bFit")
        self.horizontalLayout.addWidget(self.bFit)
        self.pushButton_check_softw_gates = QtWidgets.QPushButton(InteractiveFit)
        self.pushButton_check_softw_gates.setObjectName("pushButton_check_softw_gates")
        self.horizontalLayout.addWidget(self.pushButton_check_softw_gates)
        self.bReset = QtWidgets.QPushButton(InteractiveFit)
        self.bReset.setObjectName("bReset")
        self.horizontalLayout.addWidget(self.bReset)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(25, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(InteractiveFit)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.bFontSize = QtWidgets.QSpinBox(InteractiveFit)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bFontSize.setFont(font)
        self.bFontSize.setMinimum(1)
        self.bFontSize.setMaximum(100)
        self.bFontSize.setProperty("value", 10)
        self.bFontSize.setObjectName("bFontSize")
        self.horizontalLayout_2.addWidget(self.bFontSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(InteractiveFit)
        QtCore.QMetaObject.connectSlotsByName(InteractiveFit)

    def retranslateUi(self, InteractiveFit):
        _translate = QtCore.QCoreApplication.translate
        InteractiveFit.setWindowTitle(_translate("InteractiveFit", "Form"))
        self.bLoad.setText(_translate("InteractiveFit", "Load"))
        item = self.parTable.horizontalHeaderItem(0)
        item.setText(_translate("InteractiveFit", "Parameter"))
        item = self.parTable.horizontalHeaderItem(1)
        item.setText(_translate("InteractiveFit", "Value"))
        item = self.parTable.horizontalHeaderItem(2)
        item.setText(_translate("InteractiveFit", "Fixed"))
        self.bFit.setText(_translate("InteractiveFit", "Fit"))
        self.pushButton_check_softw_gates.setText(_translate("InteractiveFit", "check software gates"))
        self.bReset.setText(_translate("InteractiveFit", "Reset"))
        self.label.setText(_translate("InteractiveFit", "Font size"))

