# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Users\Patrick\Documents\Python Projects\Tilda\PolliFit\source\Gui\Ui_Moments.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Moments(object):
    def setupUi(self, Moments):
        Moments.setObjectName("Moments")
        Moments.resize(733, 576)
        Moments.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Moments)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(Moments)
        self.label_8.setMinimumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.dip_frame = QtWidgets.QFrame(Moments)
        self.dip_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dip_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dip_frame.setLineWidth(2)
        self.dip_frame.setObjectName("dip_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dip_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.dip_frame)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_21 = QtWidgets.QLabel(self.dip_frame)
        self.label_21.setMinimumSize(QtCore.QSize(120, 0))
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spin = QtWidgets.QDoubleSpinBox(self.dip_frame)
        self.spin.setDecimals(1)
        self.spin.setMaximum(50.0)
        self.spin.setSingleStep(0.5)
        self.spin.setProperty("value", 0.5)
        self.spin.setObjectName("spin")
        self.horizontalLayout_2.addWidget(self.spin)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.dip_frame)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.dip_frame)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ARef = QtWidgets.QLineEdit(self.dip_frame)
        self.ARef.setObjectName("ARef")
        self.horizontalLayout_9.addWidget(self.ARef)
        self.pm_a = QtWidgets.QLabel(self.dip_frame)
        self.pm_a.setAlignment(QtCore.Qt.AlignCenter)
        self.pm_a.setObjectName("pm_a")
        self.horizontalLayout_9.addWidget(self.pm_a)
        self.ARef_err = QtWidgets.QLineEdit(self.dip_frame)
        self.ARef_err.setObjectName("ARef_err")
        self.horizontalLayout_9.addWidget(self.ARef_err)
        self.label_5 = QtWidgets.QLabel(self.dip_frame)
        self.label_5.setMinimumSize(QtCore.QSize(35, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.muRef = QtWidgets.QLineEdit(self.dip_frame)
        self.muRef.setObjectName("muRef")
        self.horizontalLayout_10.addWidget(self.muRef)
        self.pm_mu = QtWidgets.QLabel(self.dip_frame)
        self.pm_mu.setAlignment(QtCore.Qt.AlignCenter)
        self.pm_mu.setObjectName("pm_mu")
        self.horizontalLayout_10.addWidget(self.pm_mu)
        self.muRef_err = QtWidgets.QLineEdit(self.dip_frame)
        self.muRef_err.setObjectName("muRef_err")
        self.horizontalLayout_10.addWidget(self.muRef_err)
        self.label_4 = QtWidgets.QLabel(self.dip_frame)
        self.label_4.setMinimumSize(QtCore.QSize(35, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.verticalLayout.addLayout(self.formLayout)
        self.saveMuRef = QtWidgets.QPushButton(self.dip_frame)
        self.saveMuRef.setObjectName("saveMuRef")
        self.verticalLayout.addWidget(self.saveMuRef)
        self.cMuRef = QtWidgets.QCheckBox(self.dip_frame)
        self.cMuRef.setChecked(True)
        self.cMuRef.setObjectName("cMuRef")
        self.verticalLayout.addWidget(self.cMuRef)
        self.verticalLayout_2.addWidget(self.dip_frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Moments)
        self.label_7.setMinimumSize(QtCore.QSize(30, 0))
        self.label_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.groupBox = QtWidgets.QGroupBox(Moments)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LowerA = QtWidgets.QRadioButton(self.groupBox)
        self.LowerA.setChecked(False)
        self.LowerA.setObjectName("LowerA")
        self.horizontalLayout.addWidget(self.LowerA)
        self.UpperA = QtWidgets.QRadioButton(self.groupBox)
        self.UpperA.setChecked(True)
        self.UpperA.setObjectName("UpperA")
        self.horizontalLayout.addWidget(self.UpperA)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.bCalcMagneticMoment = QtWidgets.QPushButton(Moments)
        self.bCalcMagneticMoment.setMinimumSize(QtCore.QSize(200, 0))
        self.bCalcMagneticMoment.setObjectName("bCalcMagneticMoment")
        self.horizontalLayout_3.addWidget(self.bCalcMagneticMoment)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(Moments)
        self.label_6.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(Moments)
        self.label_9.setMinimumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.quad_frame = QtWidgets.QFrame(Moments)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quad_frame.sizePolicy().hasHeightForWidth())
        self.quad_frame.setSizePolicy(sizePolicy)
        self.quad_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quad_frame.setLineWidth(2)
        self.quad_frame.setMidLineWidth(0)
        self.quad_frame.setObjectName("quad_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.quad_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.quad_frame)
        self.label_10.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setIndent(1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.quad_frame)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.BRef = QtWidgets.QLineEdit(self.quad_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BRef.sizePolicy().hasHeightForWidth())
        self.BRef.setSizePolicy(sizePolicy)
        self.BRef.setObjectName("BRef")
        self.horizontalLayout_11.addWidget(self.BRef)
        self.label_16 = QtWidgets.QLabel(self.quad_frame)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.BRef_err = QtWidgets.QLineEdit(self.quad_frame)
        self.BRef_err.setObjectName("BRef_err")
        self.horizontalLayout_11.addWidget(self.BRef_err)
        self.label_12 = QtWidgets.QLabel(self.quad_frame)
        self.label_12.setMinimumSize(QtCore.QSize(35, 0))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_13 = QtWidgets.QLabel(self.quad_frame)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_17 = QtWidgets.QLabel(self.quad_frame)
        self.label_17.setMinimumSize(QtCore.QSize(120, 0))
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.QRef = QtWidgets.QLineEdit(self.quad_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QRef.sizePolicy().hasHeightForWidth())
        self.QRef.setSizePolicy(sizePolicy)
        self.QRef.setObjectName("QRef")
        self.horizontalLayout_12.addWidget(self.QRef)
        self.label_19 = QtWidgets.QLabel(self.quad_frame)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.QRef_err = QtWidgets.QLineEdit(self.quad_frame)
        self.QRef_err.setObjectName("QRef_err")
        self.horizontalLayout_12.addWidget(self.QRef_err)
        self.label_14 = QtWidgets.QLabel(self.quad_frame)
        self.label_14.setMinimumSize(QtCore.QSize(35, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.eVzz = QtWidgets.QLineEdit(self.quad_frame)
        self.eVzz.setObjectName("eVzz")
        self.horizontalLayout_13.addWidget(self.eVzz)
        self.label_20 = QtWidgets.QLabel(self.quad_frame)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.eVzz_err = QtWidgets.QLineEdit(self.quad_frame)
        self.eVzz_err.setObjectName("eVzz_err")
        self.horizontalLayout_13.addWidget(self.eVzz_err)
        self.label_18 = QtWidgets.QLabel(self.quad_frame)
        self.label_18.setMinimumSize(QtCore.QSize(35, 0))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.verticalLayout_10.addLayout(self.formLayout_2)
        self.saveQRef = QtWidgets.QPushButton(self.quad_frame)
        self.saveQRef.setObjectName("saveQRef")
        self.verticalLayout_10.addWidget(self.saveQRef)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cQRef = QtWidgets.QCheckBox(self.quad_frame)
        self.cQRef.setChecked(True)
        self.cQRef.setObjectName("cQRef")
        self.horizontalLayout_5.addWidget(self.cQRef)
        self.label_22 = QtWidgets.QLabel(self.quad_frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.quad_frame)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(Moments)
        self.label_15.setMinimumSize(QtCore.QSize(30, 0))
        self.label_15.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.groupBox1 = QtWidgets.QGroupBox(Moments)
        self.groupBox1.setObjectName("groupBox1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.LowerB = QtWidgets.QRadioButton(self.groupBox1)
        self.LowerB.setChecked(False)
        self.LowerB.setObjectName("LowerB")
        self.horizontalLayout_8.addWidget(self.LowerB)
        self.UpperB = QtWidgets.QRadioButton(self.groupBox1)
        self.UpperB.setChecked(True)
        self.UpperB.setObjectName("UpperB")
        self.horizontalLayout_8.addWidget(self.UpperB)
        self.horizontalLayout_7.addWidget(self.groupBox1)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.bCalcQ = QtWidgets.QPushButton(Moments)
        self.bCalcQ.setMinimumSize(QtCore.QSize(200, 0))
        self.bCalcQ.setObjectName("bCalcQ")
        self.horizontalLayout_6.addWidget(self.bCalcQ)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.dip_frame.raise_()
        self.quad_frame.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_9.raise_()

        self.retranslateUi(Moments)
        QtCore.QMetaObject.connectSlotsByName(Moments)

    def retranslateUi(self, Moments):
        _translate = QtCore.QCoreApplication.translate
        Moments.setWindowTitle(_translate("Moments", "Form"))
        self.label_8.setText(_translate("Moments", "Magnetic dipole moments"))
        self.label.setText(_translate("Moments", "Reference values:"))
        self.label_21.setText(_translate("Moments", "Nuclear Spin I:"))
        self.label_2.setText(_translate("Moments", "Hyperfine parameter A:"))
        self.label_3.setText(_translate("Moments", "Magnetic dipole moment <nobr>&mu;</nobr>:"))
        self.pm_a.setText(_translate("Moments", "<nobr> &plusmn;</nobr>"))
        self.label_5.setText(_translate("Moments", "MHz"))
        self.pm_mu.setText(_translate("Moments", "<nobr> &plusmn;</nobr>"))
        self.label_4.setText(_translate("Moments", "<nobr>&mu;_N</nobr>"))
        self.saveMuRef.setText(_translate("Moments", "save to db"))
        self.cMuRef.setText(_translate("Moments", "take reference from database"))
        self.label_7.setText(_translate("Moments", "use"))
        self.LowerA.setText(_translate("Moments", "Lower A"))
        self.UpperA.setText(_translate("Moments", "Upper A"))
        self.bCalcMagneticMoment.setText(_translate("Moments", "calculate magnetic dipole moments"))
        self.label_6.setText(_translate("Moments", "CAUTION! No hyperfine anomaly assumed!"))
        self.label_9.setText(_translate("Moments", "Electric quadrupole moments"))
        self.label_10.setText(_translate("Moments", "Reference values:"))
        self.label_11.setText(_translate("Moments", "Hyperfine parameter B:"))
        self.label_16.setText(_translate("Moments", "<nobr> &plusmn;</nobr>"))
        self.label_12.setText(_translate("Moments", "MHz"))
        self.label_13.setText(_translate("Moments", "Quadrupole moment Q:"))
        self.label_17.setText(_translate("Moments", "--> eVzz :"))
        self.label_19.setText(_translate("Moments", "<nobr> &plusmn;</nobr>"))
        self.label_14.setText(_translate("Moments", "b"))
        self.label_20.setText(_translate("Moments", "<nobr> &plusmn;</nobr>"))
        self.label_18.setText(_translate("Moments", "b/MHz"))
        self.saveQRef.setText(_translate("Moments", "save to db"))
        self.cQRef.setText(_translate("Moments", "take reference from database"))
        self.label_22.setText(_translate("Moments", "Specify either B and Q or eVzz here. The database only uses eVzz."))
        self.label_15.setText(_translate("Moments", "use"))
        self.LowerB.setText(_translate("Moments", "Lower B"))
        self.UpperB.setText(_translate("Moments", "Upper B"))
        self.bCalcQ.setText(_translate("Moments", "calculate electric quadrupole moments"))
