# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Simulation.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Simulation(object):
    def setupUi(self, Simulation):
        Simulation.setObjectName("Simulation")
        Simulation.resize(588, 379)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Simulation)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Simulation)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listIsotopes = QtWidgets.QListWidget(Simulation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listIsotopes.sizePolicy().hasHeightForWidth())
        self.listIsotopes.setSizePolicy(sizePolicy)
        self.listIsotopes.setAlternatingRowColors(False)
        self.listIsotopes.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listIsotopes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listIsotopes.setViewMode(QtWidgets.QListView.ListMode)
        self.listIsotopes.setModelColumn(0)
        self.listIsotopes.setObjectName("listIsotopes")
        item = QtWidgets.QListWidgetItem()
        self.listIsotopes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listIsotopes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listIsotopes.addItem(item)
        self.verticalLayout.addWidget(self.listIsotopes)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dAcolFreq = QtWidgets.QDoubleSpinBox(Simulation)
        self.dAcolFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dAcolFreq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dAcolFreq.setDecimals(0)
        self.dAcolFreq.setMaximum(999999999999999.0)
        self.dAcolFreq.setObjectName("dAcolFreq")
        self.gridLayout.addWidget(self.dAcolFreq, 2, 1, 1, 1)
        self.cColFreq = QtWidgets.QCheckBox(Simulation)
        self.cColFreq.setObjectName("cColFreq")
        self.gridLayout.addWidget(self.cColFreq, 1, 0, 1, 1)
        self.dColFreq = QtWidgets.QDoubleSpinBox(Simulation)
        self.dColFreq.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.dColFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dColFreq.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dColFreq.setDecimals(0)
        self.dColFreq.setMaximum(999999999999999.0)
        self.dColFreq.setObjectName("dColFreq")
        self.gridLayout.addWidget(self.dColFreq, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Simulation)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.cAcolFreq = QtWidgets.QCheckBox(Simulation)
        self.cAcolFreq.setObjectName("cAcolFreq")
        self.gridLayout.addWidget(self.cAcolFreq, 2, 0, 1, 1)
        self.coLineVar = QtWidgets.QComboBox(Simulation)
        self.coLineVar.setObjectName("coLineVar")
        self.coLineVar.addItem("")
        self.coLineVar.addItem("")
        self.gridLayout.addWidget(self.coLineVar, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Simulation)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.cInFreq = QtWidgets.QCheckBox(Simulation)
        self.cInFreq.setText("")
        self.cInFreq.setObjectName("cInFreq")
        self.gridLayout.addWidget(self.cInFreq, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.pShow = QtWidgets.QPushButton(Simulation)
        self.pShow.setObjectName("pShow")
        self.verticalLayout.addWidget(self.pShow)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(Simulation)
        QtCore.QMetaObject.connectSlotsByName(Simulation)

    def retranslateUi(self, Simulation):
        _translate = QtCore.QCoreApplication.translate
        Simulation.setWindowTitle(_translate("Simulation", "Form"))
        self.label.setText(_translate("Simulation", "Collinear Spectrum Simulation"))
        __sortingEnabled = self.listIsotopes.isSortingEnabled()
        self.listIsotopes.setSortingEnabled(False)
        item = self.listIsotopes.item(0)
        item.setText(_translate("Simulation", "test1"))
        item = self.listIsotopes.item(1)
        item.setText(_translate("Simulation", "test2"))
        item = self.listIsotopes.item(2)
        item.setText(_translate("Simulation", "test3"))
        self.listIsotopes.setSortingEnabled(__sortingEnabled)
        self.cColFreq.setText(_translate("Simulation", "Col. LaserFreq / MHz:"))
        self.label_2.setText(_translate("Simulation", "LineVar:"))
        self.cAcolFreq.setText(_translate("Simulation", "ACol. LaserFreq / MHz:"))
        self.coLineVar.setItemText(0, _translate("Simulation", "b1"))
        self.coLineVar.setItemText(1, _translate("Simulation", "b2"))
        self.label_3.setText(_translate("Simulation", "In Frequency?"))
        self.pShow.setText(_translate("Simulation", "Show spectrum"))

