# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Version.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Version(object):
    def setupUi(self, Version):
        Version.setObjectName("Version")
        Version.resize(345, 247)
        Version.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout_2 = QtWidgets.QGridLayout(Version)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelDateFix = QtWidgets.QLabel(Version)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateFix.sizePolicy().hasHeightForWidth())
        self.labelDateFix.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDateFix.setFont(font)
        self.labelDateFix.setObjectName("labelDateFix")
        self.gridLayout.addWidget(self.labelDateFix, 1, 0, 1, 1)
        self.labelDate = QtWidgets.QLabel(Version)
        self.labelDate.setObjectName("labelDate")
        self.gridLayout.addWidget(self.labelDate, 1, 1, 1, 1)
        self.labelVersion = QtWidgets.QLabel(Version)
        self.labelVersion.setObjectName("labelVersion")
        self.gridLayout.addWidget(self.labelVersion, 0, 1, 1, 1)
        self.labelVersionFix = QtWidgets.QLabel(Version)
        self.labelVersionFix.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVersionFix.sizePolicy().hasHeightForWidth())
        self.labelVersionFix.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelVersionFix.setFont(font)
        self.labelVersionFix.setObjectName("labelVersionFix")
        self.gridLayout.addWidget(self.labelVersionFix, 0, 0, 1, 1)
        self.labelCommitFix = QtWidgets.QLabel(Version)
        self.labelCommitFix.setObjectName("labelCommitFix")
        self.gridLayout.addWidget(self.labelCommitFix, 4, 0, 1, 1)
        self.labelBranch = QtWidgets.QLabel(Version)
        self.labelBranch.setObjectName("labelBranch")
        self.gridLayout.addWidget(self.labelBranch, 3, 1, 1, 1)
        self.labelCommit = QtWidgets.QLabel(Version)
        self.labelCommit.setObjectName("labelCommit")
        self.gridLayout.addWidget(self.labelCommit, 4, 1, 1, 1)
        self.labelBranchFix = QtWidgets.QLabel(Version)
        font = QtGui.QFont()
        font.setItalic(False)
        self.labelBranchFix.setFont(font)
        self.labelBranchFix.setObjectName("labelBranchFix")
        self.gridLayout.addWidget(self.labelBranchFix, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(Version)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButton_whatsNew = QtWidgets.QPushButton(Version)
        self.pushButton_whatsNew.setObjectName("pushButton_whatsNew")
        self.gridLayout_2.addWidget(self.pushButton_whatsNew, 1, 0, 1, 1)

        self.retranslateUi(Version)
        QtCore.QMetaObject.connectSlotsByName(Version)

    def retranslateUi(self, Version):
        _translate = QtCore.QCoreApplication.translate
        Version.setWindowTitle(_translate("Version", "Version"))
        self.labelDateFix.setText(_translate("Version", "Date:"))
        self.labelDate.setText(_translate("Version", "TextLabel"))
        self.labelVersion.setText(_translate("Version", "TextLabel"))
        self.labelVersionFix.setText(_translate("Version", "Version:"))
        self.labelCommitFix.setText(_translate("Version", "Commit:"))
        self.labelBranch.setText(_translate("Version", "TextLabel"))
        self.labelCommit.setText(_translate("Version", "TextLabel"))
        self.labelBranchFix.setText(_translate("Version", "Branch:"))
        self.pushButton_whatsNew.setText(_translate("Version", "what\'s new?"))

