# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_PpgSimpleWidg.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PpgSimpleWidg(object):
    def setupUi(self, PpgSimpleWidg):
        PpgSimpleWidg.setObjectName("PpgSimpleWidg")
        PpgSimpleWidg.resize(556, 553)
        PpgSimpleWidg.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(PpgSimpleWidg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(PpgSimpleWidg)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBox_proton_trig_yes_no = QtWidgets.QComboBox(PpgSimpleWidg)
        self.comboBox_proton_trig_yes_no.setObjectName("comboBox_proton_trig_yes_no")
        self.horizontalLayout_5.addWidget(self.comboBox_proton_trig_yes_no)
        self.label_3 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.comboBox_proton_trig_input_ch = QtWidgets.QComboBox(PpgSimpleWidg)
        self.comboBox_proton_trig_input_ch.setObjectName("comboBox_proton_trig_input_ch")
        self.horizontalLayout_5.addWidget(self.comboBox_proton_trig_input_ch)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_2 = QtWidgets.QFrame(PpgSimpleWidg)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_6 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_rfqcb_release_time_ms = QtWidgets.QDoubleSpinBox(PpgSimpleWidg)
        self.doubleSpinBox_rfqcb_release_time_ms.setKeyboardTracking(False)
        self.doubleSpinBox_rfqcb_release_time_ms.setDecimals(5)
        self.doubleSpinBox_rfqcb_release_time_ms.setMaximum(10000.0)
        self.doubleSpinBox_rfqcb_release_time_ms.setObjectName("doubleSpinBox_rfqcb_release_time_ms")
        self.gridLayout.addWidget(self.doubleSpinBox_rfqcb_release_time_ms, 1, 10, 1, 1)
        self.label_14 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 1, 1, 1)
        self.doubleSpinBox_rfqcb_acc_time_ms = QtWidgets.QDoubleSpinBox(PpgSimpleWidg)
        self.doubleSpinBox_rfqcb_acc_time_ms.setKeyboardTracking(False)
        self.doubleSpinBox_rfqcb_acc_time_ms.setDecimals(5)
        self.doubleSpinBox_rfqcb_acc_time_ms.setMaximum(10000.0)
        self.doubleSpinBox_rfqcb_acc_time_ms.setObjectName("doubleSpinBox_rfqcb_acc_time_ms")
        self.gridLayout.addWidget(self.doubleSpinBox_rfqcb_acc_time_ms, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.doubleSpinBox_rfqcb_delay_ms = QtWidgets.QDoubleSpinBox(PpgSimpleWidg)
        self.doubleSpinBox_rfqcb_delay_ms.setKeyboardTracking(False)
        self.doubleSpinBox_rfqcb_delay_ms.setDecimals(5)
        self.doubleSpinBox_rfqcb_delay_ms.setMaximum(10000.0)
        self.doubleSpinBox_rfqcb_delay_ms.setObjectName("doubleSpinBox_rfqcb_delay_ms")
        self.gridLayout.addWidget(self.doubleSpinBox_rfqcb_delay_ms, 1, 2, 1, 1)
        self.spinBox_rfqcb_num_of_bunches = QtWidgets.QSpinBox(PpgSimpleWidg)
        self.spinBox_rfqcb_num_of_bunches.setKeyboardTracking(False)
        self.spinBox_rfqcb_num_of_bunches.setMaximum(10000000)
        self.spinBox_rfqcb_num_of_bunches.setObjectName("spinBox_rfqcb_num_of_bunches")
        self.gridLayout.addWidget(self.spinBox_rfqcb_num_of_bunches, 0, 10, 1, 1)
        self.label_13 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 5, 1, 1)
        self.comboBox_rfqcb_out_ch = QtWidgets.QComboBox(PpgSimpleWidg)
        self.comboBox_rfqcb_out_ch.setObjectName("comboBox_rfqcb_out_ch")
        self.gridLayout.addWidget(self.comboBox_rfqcb_out_ch, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.comboBox_rfq_state = QtWidgets.QComboBox(PpgSimpleWidg)
        self.comboBox_rfq_state.setObjectName("comboBox_rfq_state")
        self.gridLayout.addWidget(self.comboBox_rfq_state, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(PpgSimpleWidg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_8 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        self.comboBox_beam_gate_state = QtWidgets.QComboBox(PpgSimpleWidg)
        self.comboBox_beam_gate_state.setObjectName("comboBox_beam_gate_state")
        self.gridLayout_2.addWidget(self.comboBox_beam_gate_state, 0, 1, 1, 1)
        self.comboBox_beam_gate_out_ch = QtWidgets.QComboBox(PpgSimpleWidg)
        self.comboBox_beam_gate_out_ch.setObjectName("comboBox_beam_gate_out_ch")
        self.gridLayout_2.addWidget(self.comboBox_beam_gate_out_ch, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.doubleSpinBox_beam_gate_delay_ms = QtWidgets.QDoubleSpinBox(PpgSimpleWidg)
        self.doubleSpinBox_beam_gate_delay_ms.setKeyboardTracking(False)
        self.doubleSpinBox_beam_gate_delay_ms.setDecimals(5)
        self.doubleSpinBox_beam_gate_delay_ms.setMaximum(10000.0)
        self.doubleSpinBox_beam_gate_delay_ms.setObjectName("doubleSpinBox_beam_gate_delay_ms")
        self.gridLayout_2.addWidget(self.doubleSpinBox_beam_gate_delay_ms, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(PpgSimpleWidg)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.doubleSpinBox_beam_gate_open_ms = QtWidgets.QDoubleSpinBox(PpgSimpleWidg)
        self.doubleSpinBox_beam_gate_open_ms.setKeyboardTracking(False)
        self.doubleSpinBox_beam_gate_open_ms.setDecimals(5)
        self.doubleSpinBox_beam_gate_open_ms.setMaximum(10000.0)
        self.doubleSpinBox_beam_gate_open_ms.setObjectName("doubleSpinBox_beam_gate_open_ms")
        self.gridLayout_2.addWidget(self.doubleSpinBox_beam_gate_open_ms, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(PpgSimpleWidg)
        QtCore.QMetaObject.connectSlotsByName(PpgSimpleWidg)

    def retranslateUi(self, PpgSimpleWidg):
        _translate = QtCore.QCoreApplication.translate
        PpgSimpleWidg.setWindowTitle(_translate("PpgSimpleWidg", "Form"))
        self.label_2.setText(_translate("PpgSimpleWidg", "proton trigger"))
        self.label.setText(_translate("PpgSimpleWidg", "proton triggered:"))
        self.label_3.setText(_translate("PpgSimpleWidg", "proton trig input:"))
        self.label_6.setText(_translate("PpgSimpleWidg", "RFQCB"))
        self.label_14.setText(_translate("PpgSimpleWidg", "delay [ms]:"))
        self.label_5.setText(_translate("PpgSimpleWidg", "release time [ms]:"))
        self.label_4.setText(_translate("PpgSimpleWidg", "accumulation time [ms]:"))
        self.label_13.setText(_translate("PpgSimpleWidg", "number of bunches:"))
        self.label_7.setText(_translate("PpgSimpleWidg", "output channel:"))
        self.label_15.setText(_translate("PpgSimpleWidg", "rfq state:"))
        self.label_8.setText(_translate("PpgSimpleWidg", "beam gate"))
        self.label_9.setText(_translate("PpgSimpleWidg", "beamgate state:"))
        self.label_12.setText(_translate("PpgSimpleWidg", "output channel:"))
        self.label_10.setText(_translate("PpgSimpleWidg", "delay [ms]:"))
        self.label_11.setText(_translate("PpgSimpleWidg", "open [ms]:"))

