# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_TildaPassive.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TildaPassiveMainWindow(object):
    def setupUi(self, TildaPassiveMainWindow):
        TildaPassiveMainWindow.setObjectName("TildaPassiveMainWindow")
        TildaPassiveMainWindow.resize(352, 399)
        TildaPassiveMainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(TildaPassiveMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setMinimumSize(QtCore.QSize(0, 50))
        self.label_status.setAutoFillBackground(True)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_acq_steps_total = QtWidgets.QLabel(self.centralwidget)
        self.label_acq_steps_total.setObjectName("label_acq_steps_total")
        self.gridLayout_3.addWidget(self.label_acq_steps_total, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_acq_scans_total = QtWidgets.QLabel(self.centralwidget)
        self.label_acq_scans_total.setObjectName("label_acq_scans_total")
        self.gridLayout_3.addWidget(self.label_acq_scans_total, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 3, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_delay = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_delay.setKeyboardTracking(False)
        self.doubleSpinBox_delay.setMaximum(9999999.0)
        self.doubleSpinBox_delay.setProperty("value", 50.0)
        self.doubleSpinBox_delay.setObjectName("doubleSpinBox_delay")
        self.gridLayout_2.addWidget(self.doubleSpinBox_delay, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_save_settings = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save_settings.sizePolicy().hasHeightForWidth())
        self.pushButton_save_settings.setSizePolicy(sizePolicy)
        self.pushButton_save_settings.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_save_settings.setObjectName("pushButton_save_settings")
        self.gridLayout_2.addWidget(self.pushButton_save_settings, 2, 1, 1, 1)
        self.doubleSpinBox_num_of_bins = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_num_of_bins.setMaximum(200.0)
        self.doubleSpinBox_num_of_bins.setProperty("value", 10.0)
        self.doubleSpinBox_num_of_bins.setObjectName("doubleSpinBox_num_of_bins")
        self.gridLayout_2.addWidget(self.doubleSpinBox_num_of_bins, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout.addWidget(self.pushButton_stop, 3, 0, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_last_saved = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_last_saved.sizePolicy().hasHeightForWidth())
        self.label_last_saved.setSizePolicy(sizePolicy)
        self.label_last_saved.setObjectName("label_last_saved")
        self.verticalLayout.addWidget(self.label_last_saved)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.cOut = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cOut.setMinimumSize(QtCore.QSize(200, 0))
        self.cOut.setMaximumSize(QtCore.QSize(16777215, 200))
        self.cOut.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.cOut.setMaximumBlockCount(500)
        self.cOut.setObjectName("cOut")
        self.verticalLayout.addWidget(self.cOut)
        TildaPassiveMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TildaPassiveMainWindow)
        QtCore.QMetaObject.connectSlotsByName(TildaPassiveMainWindow)

    def retranslateUi(self, TildaPassiveMainWindow):
        _translate = QtCore.QCoreApplication.translate
        TildaPassiveMainWindow.setWindowTitle(_translate("TildaPassiveMainWindow", "MainWindow"))
        self.label_status.setText(_translate("TildaPassiveMainWindow", "Status"))
        self.label_acq_steps_total.setText(_translate("TildaPassiveMainWindow", "None"))
        self.label_4.setText(_translate("TildaPassiveMainWindow", "progress of scan:"))
        self.label_5.setText(_translate("TildaPassiveMainWindow", "number of acq. steps:"))
        self.label_7.setText(_translate("TildaPassiveMainWindow", "number of acq. scans:"))
        self.label_acq_scans_total.setText(_translate("TildaPassiveMainWindow", "None"))
        self.label.setText(_translate("TildaPassiveMainWindow", "dwell time [µs]:"))
        self.label_2.setText(_translate("TildaPassiveMainWindow", "delay [µs]:"))
        self.pushButton_save_settings.setText(_translate("TildaPassiveMainWindow", "save settings"))
        self.doubleSpinBox_num_of_bins.setToolTip(_translate("TildaPassiveMainWindow", "the dwell time is split into bins of 10ns"))
        self.label_9.setText(_translate("TildaPassiveMainWindow", "*always start before MCP!"))
        self.pushButton_stop.setText(_translate("TildaPassiveMainWindow", "Stop and Save"))
        self.pushButton_start.setText(_translate("TildaPassiveMainWindow", "Start*"))
        self.label_10.setText(_translate("TildaPassiveMainWindow", "save together with MCP!"))
        self.label_6.setText(_translate("TildaPassiveMainWindow", "last saved:"))
        self.label_last_saved.setText(_translate("TildaPassiveMainWindow", "None"))
        self.label_3.setText(_translate("TildaPassiveMainWindow", "live feed of raw data:"))

