# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Options.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Options(object):
    def setupUi(self, Dialog_Options):
        Dialog_Options.setObjectName("Dialog_Options")
        Dialog_Options.resize(555, 501)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Options)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog_Options)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_generalSettings = QtWidgets.QWidget()
        self.tab_generalSettings.setObjectName("tab_generalSettings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_generalSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_Connect = QtWidgets.QGroupBox(self.tab_generalSettings)
        self.groupBox_Connect.setObjectName("groupBox_Connect")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Connect)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.link_openFpgaConfig = QtWidgets.QCommandLinkButton(self.groupBox_Connect)
        self.link_openFpgaConfig.setObjectName("link_openFpgaConfig")
        self.verticalLayout_4.addWidget(self.link_openFpgaConfig)
        self.line = QtWidgets.QFrame(self.groupBox_Connect)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.link_openTritonConfig = QtWidgets.QCommandLinkButton(self.groupBox_Connect)
        self.link_openTritonConfig.setObjectName("link_openTritonConfig")
        self.verticalLayout_4.addWidget(self.link_openTritonConfig)
        self.checkBox_disableTritonLink = QtWidgets.QCheckBox(self.groupBox_Connect)
        self.checkBox_disableTritonLink.setObjectName("checkBox_disableTritonLink")
        self.verticalLayout_4.addWidget(self.checkBox_disableTritonLink)
        self.verticalLayout_2.addWidget(self.groupBox_Connect)
        self.groupBox_Sound = QtWidgets.QGroupBox(self.tab_generalSettings)
        self.groupBox_Sound.setObjectName("groupBox_Sound")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_Sound)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_playSound = QtWidgets.QCheckBox(self.groupBox_Sound)
        self.checkBox_playSound.setObjectName("checkBox_playSound")
        self.verticalLayout_3.addWidget(self.checkBox_playSound)
        self.link_openSoundsFolder = QtWidgets.QCommandLinkButton(self.groupBox_Sound)
        self.link_openSoundsFolder.setObjectName("link_openSoundsFolder")
        self.verticalLayout_3.addWidget(self.link_openSoundsFolder)
        self.pushButton_chooseSoundsFolder = QtWidgets.QPushButton(self.groupBox_Sound)
        self.pushButton_chooseSoundsFolder.setObjectName("pushButton_chooseSoundsFolder")
        self.verticalLayout_3.addWidget(self.pushButton_chooseSoundsFolder)
        self.verticalLayout_2.addWidget(self.groupBox_Sound)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_generalSettings, "")
        self.tab_polliFit = QtWidgets.QWidget()
        self.tab_polliFit.setObjectName("tab_polliFit")
        self.tabWidget.addTab(self.tab_polliFit, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox_okCancel = QtWidgets.QDialogButtonBox(Dialog_Options)
        self.buttonBox_okCancel.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_okCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttonBox_okCancel.setObjectName("buttonBox_okCancel")
        self.verticalLayout.addWidget(self.buttonBox_okCancel)

        self.retranslateUi(Dialog_Options)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox_okCancel.accepted.connect(Dialog_Options.accept)
        self.buttonBox_okCancel.rejected.connect(Dialog_Options.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Options)

    def retranslateUi(self, Dialog_Options):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Options.setWindowTitle(_translate("Dialog_Options", "TILDA Options"))
        self.groupBox_Connect.setTitle(_translate("Dialog_Options", "CONNECT"))
        self.link_openFpgaConfig.setText(_translate("Dialog_Options", "...\\TildaHost\\source\\Driver\\DataAcquisitionFpga\\fpga_config.xml"))
        self.link_openFpgaConfig.setDescription(_translate("Dialog_Options", "Open fpga config to change the FPGA configuration for this system"))
        self.link_openTritonConfig.setText(_translate("Dialog_Options", "...\\TildaHost\\source\\Driver\\TritonListener\\TritonConfig.py"))
        self.link_openTritonConfig.setDescription(_translate("Dialog_Options", "Open config file to change the Triton configuration"))
        self.checkBox_disableTritonLink.setText(_translate("Dialog_Options", "DISABLE all Triton functionality (\"local\")"))
        self.groupBox_Sound.setTitle(_translate("Dialog_Options", "SOUND"))
        self.checkBox_playSound.setText(_translate("Dialog_Options", "Play random sound after each successful scan"))
        self.link_openSoundsFolder.setText(_translate("Dialog_Options", "...\\TildaHost\\source\\Interface\\Sounds"))
        self.link_openSoundsFolder.setDescription(_translate("Dialog_Options", "Go to Folder to add or remove sounds from the random rotation."))
        self.pushButton_chooseSoundsFolder.setText(_translate("Dialog_Options", "Choose Sounds Folder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_generalSettings), _translate("Dialog_Options", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_polliFit), _translate("Dialog_Options", "PolliFit"))
