# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_LiveDataPlotting.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_LiveDataPlotting(object):
    def setupUi(self, MainWindow_LiveDataPlotting):
        MainWindow_LiveDataPlotting.setObjectName("MainWindow_LiveDataPlotting")
        MainWindow_LiveDataPlotting.resize(737, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow_LiveDataPlotting)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_sum = QtWidgets.QWidget()
        self.tab_sum.setObjectName("tab_sum")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_sum)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_outer_sum_plot = QtWidgets.QWidget(self.tab_sum)
        self.widget_outer_sum_plot.setObjectName("widget_outer_sum_plot")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_outer_sum_plot)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_inner_sum_plot = QtWidgets.QWidget(self.widget_outer_sum_plot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_inner_sum_plot.sizePolicy().hasHeightForWidth())
        self.widget_inner_sum_plot.setSizePolicy(sizePolicy)
        self.widget_inner_sum_plot.setObjectName("widget_inner_sum_plot")
        self.horizontalLayout.addWidget(self.widget_inner_sum_plot)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(-1, -1, 50, -1)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_outer_sum_plot)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.comboBox_select_sum_for_pmts = QtWidgets.QComboBox(self.widget_outer_sum_plot)
        self.comboBox_select_sum_for_pmts.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_select_sum_for_pmts.setObjectName("comboBox_select_sum_for_pmts")
        self.verticalLayout_3.addWidget(self.comboBox_select_sum_for_pmts)
        self.lineEdit_arith_scaler_input = QtWidgets.QLineEdit(self.widget_outer_sum_plot)
        self.lineEdit_arith_scaler_input.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_arith_scaler_input.setObjectName("lineEdit_arith_scaler_input")
        self.verticalLayout_3.addWidget(self.lineEdit_arith_scaler_input)
        self.label_arith_scaler_set = QtWidgets.QLabel(self.widget_outer_sum_plot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_arith_scaler_set.sizePolicy().hasHeightForWidth())
        self.label_arith_scaler_set.setSizePolicy(sizePolicy)
        self.label_arith_scaler_set.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_arith_scaler_set.setObjectName("label_arith_scaler_set")
        self.verticalLayout_3.addWidget(self.label_arith_scaler_set)
        self.comboBox_sum_tr = QtWidgets.QComboBox(self.widget_outer_sum_plot)
        self.comboBox_sum_tr.setObjectName("comboBox_sum_tr")
        self.verticalLayout_3.addWidget(self.comboBox_sum_tr)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.widget_outer_sum_plot)
        self.tabWidget.addTab(self.tab_sum, "")
        self.tab_timeres = QtWidgets.QWidget()
        self.tab_timeres.setObjectName("tab_timeres")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_timeres)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_tres_plot = QtWidgets.QWidget(self.tab_timeres)
        self.widget_tres_plot.setObjectName("widget_tres_plot")
        self.verticalLayout_4.addWidget(self.widget_tres_plot)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox = QtWidgets.QSpinBox(self.tab_timeres)
        self.spinBox.setKeyboardTracking(False)
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(10000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_timeres)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton_save_after_scan = QtWidgets.QPushButton(self.tab_timeres)
        self.pushButton_save_after_scan.setObjectName("pushButton_save_after_scan")
        self.gridLayout.addWidget(self.pushButton_save_after_scan, 0, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.tableWidget_gates = QtWidgets.QTableWidget(self.tab_timeres)
        self.tableWidget_gates.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_gates.setObjectName("tableWidget_gates")
        self.tableWidget_gates.setColumnCount(7)
        self.tableWidget_gates.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gates.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gates.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gates.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gates.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gates.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gates.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gates.setHorizontalHeaderItem(6, item)
        self.verticalLayout_4.addWidget(self.tableWidget_gates)
        self.tabWidget.addTab(self.tab_timeres, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow_LiveDataPlotting.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_LiveDataPlotting)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_LiveDataPlotting)

    def retranslateUi(self, MainWindow_LiveDataPlotting):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_LiveDataPlotting.setWindowTitle(_translate("MainWindow_LiveDataPlotting", "MainWindow"))
        self.label.setText(_translate("MainWindow_LiveDataPlotting", "sum over:"))
        self.label_arith_scaler_set.setText(_translate("MainWindow_LiveDataPlotting", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sum), _translate("MainWindow_LiveDataPlotting", "sum"))
        self.label_4.setText(_translate("MainWindow_LiveDataPlotting", "rebinning [ns]"))
        self.pushButton_save_after_scan.setText(_translate("MainWindow_LiveDataPlotting", "Save again after scan"))
        self.tableWidget_gates.setSortingEnabled(False)
        item = self.tableWidget_gates.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_LiveDataPlotting", "track"))
        item = self.tableWidget_gates.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_LiveDataPlotting", "scaler"))
        item = self.tableWidget_gates.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_LiveDataPlotting", "v_min [V]"))
        item = self.tableWidget_gates.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_LiveDataPlotting", "v_max [V]"))
        item = self.tableWidget_gates.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow_LiveDataPlotting", "t_min [ns]"))
        item = self.tableWidget_gates.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow_LiveDataPlotting", "t_max [ns]"))
        item = self.tableWidget_gates.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow_LiveDataPlotting", "show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_timeres), _translate("MainWindow_LiveDataPlotting", "time resolved"))

