# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_TrackPar.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowTrackPars(object):
    def setupUi(self, MainWindowTrackPars):
        MainWindowTrackPars.setObjectName("MainWindowTrackPars")
        MainWindowTrackPars.resize(404, 825)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowTrackPars.sizePolicy().hasHeightForWidth())
        MainWindowTrackPars.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/track_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowTrackPars.setWindowIcon(icon)
        MainWindowTrackPars.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindowTrackPars)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.specificSequencerSettings = QtWidgets.QWidget(self.centralwidget)
        self.specificSequencerSettings.setObjectName("specificSequencerSettings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.specificSequencerSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.specificSequencerSettings)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.trigger_tab_widget = QtWidgets.QWidget(self.centralwidget)
        self.trigger_tab_widget.setEnabled(True)
        self.trigger_tab_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.trigger_tab_widget.setBaseSize(QtCore.QSize(0, 0))
        self.trigger_tab_widget.setObjectName("trigger_tab_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.trigger_tab_widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.trigger_tab_widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_trigger = QtWidgets.QWidget()
        self.tab_trigger.setObjectName("tab_trigger")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_trigger)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_descriptionTrigger = QtWidgets.QLabel(self.tab_trigger)
        self.label_descriptionTrigger.setObjectName("label_descriptionTrigger")
        self.verticalLayout_7.addWidget(self.label_descriptionTrigger)
        self.widget_trigger = QtWidgets.QWidget(self.tab_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_trigger.sizePolicy().hasHeightForWidth())
        self.widget_trigger.setSizePolicy(sizePolicy)
        self.widget_trigger.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_trigger.setObjectName("widget_trigger")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_trigger)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Trigger = QtWidgets.QLabel(self.widget_trigger)
        self.label_Trigger.setObjectName("label_Trigger")
        self.gridLayout.addWidget(self.label_Trigger, 0, 0, 1, 1)
        self.comboBox_triggerSelect = QtWidgets.QComboBox(self.widget_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_triggerSelect.sizePolicy().hasHeightForWidth())
        self.comboBox_triggerSelect.setSizePolicy(sizePolicy)
        self.comboBox_triggerSelect.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_triggerSelect.setObjectName("comboBox_triggerSelect")
        self.gridLayout.addWidget(self.comboBox_triggerSelect, 1, 0, 1, 1)
        self.checkBox_UseAllTracks = QtWidgets.QCheckBox(self.widget_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_UseAllTracks.sizePolicy().hasHeightForWidth())
        self.checkBox_UseAllTracks.setSizePolicy(sizePolicy)
        self.checkBox_UseAllTracks.setObjectName("checkBox_UseAllTracks")
        self.gridLayout.addWidget(self.checkBox_UseAllTracks, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.trigger_vert_layout = QtWidgets.QVBoxLayout()
        self.trigger_vert_layout.setObjectName("trigger_vert_layout")
        self.widget_trigger_place_holder = QtWidgets.QWidget(self.widget_trigger)
        self.widget_trigger_place_holder.setObjectName("widget_trigger_place_holder")
        self.trigger_vert_layout.addWidget(self.widget_trigger_place_holder)
        self.verticalLayout_3.addLayout(self.trigger_vert_layout)
        self.verticalLayout_7.addWidget(self.widget_trigger)
        self.tabWidget.addTab(self.tab_trigger, "")
        self.tab_step_trigger = QtWidgets.QWidget()
        self.tab_step_trigger.setObjectName("tab_step_trigger")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_step_trigger)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_descriptionStepTrigger = QtWidgets.QLabel(self.tab_step_trigger)
        self.label_descriptionStepTrigger.setObjectName("label_descriptionStepTrigger")
        self.verticalLayout_8.addWidget(self.label_descriptionStepTrigger)
        self.widget_step_trigger = QtWidgets.QWidget(self.tab_step_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_step_trigger.sizePolicy().hasHeightForWidth())
        self.widget_step_trigger.setSizePolicy(sizePolicy)
        self.widget_step_trigger.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_step_trigger.setObjectName("widget_step_trigger")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_step_trigger)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_stepTrigger = QtWidgets.QLabel(self.widget_step_trigger)
        self.label_stepTrigger.setObjectName("label_stepTrigger")
        self.gridLayout_6.addWidget(self.label_stepTrigger, 0, 0, 1, 1)
        self.comboBox_stepTriggerSelect = QtWidgets.QComboBox(self.widget_step_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_stepTriggerSelect.sizePolicy().hasHeightForWidth())
        self.comboBox_stepTriggerSelect.setSizePolicy(sizePolicy)
        self.comboBox_stepTriggerSelect.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_stepTriggerSelect.setObjectName("comboBox_stepTriggerSelect")
        self.gridLayout_6.addWidget(self.comboBox_stepTriggerSelect, 1, 0, 1, 1)
        self.checkBox_stepUseAllTracks = QtWidgets.QCheckBox(self.widget_step_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_stepUseAllTracks.sizePolicy().hasHeightForWidth())
        self.checkBox_stepUseAllTracks.setSizePolicy(sizePolicy)
        self.checkBox_stepUseAllTracks.setObjectName("checkBox_stepUseAllTracks")
        self.gridLayout_6.addWidget(self.checkBox_stepUseAllTracks, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        self.step_trigger_vert_layout = QtWidgets.QVBoxLayout()
        self.step_trigger_vert_layout.setObjectName("step_trigger_vert_layout")
        self.widget_step_trigger_place_holder = QtWidgets.QWidget(self.widget_step_trigger)
        self.widget_step_trigger_place_holder.setObjectName("widget_step_trigger_place_holder")
        self.step_trigger_vert_layout.addWidget(self.widget_step_trigger_place_holder)
        self.verticalLayout_5.addLayout(self.step_trigger_vert_layout)
        self.verticalLayout_8.addWidget(self.widget_step_trigger)
        self.tabWidget.addTab(self.tab_step_trigger, "")
        self.tab_scan_trigger = QtWidgets.QWidget()
        self.tab_scan_trigger.setObjectName("tab_scan_trigger")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_scan_trigger)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.tab_scan_trigger)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.widget_scan_trigger = QtWidgets.QWidget(self.tab_scan_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_scan_trigger.sizePolicy().hasHeightForWidth())
        self.widget_scan_trigger.setSizePolicy(sizePolicy)
        self.widget_scan_trigger.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_scan_trigger.setObjectName("widget_scan_trigger")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_scan_trigger)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_scanTrigger = QtWidgets.QLabel(self.widget_scan_trigger)
        self.label_scanTrigger.setObjectName("label_scanTrigger")
        self.gridLayout_7.addWidget(self.label_scanTrigger, 0, 0, 1, 1)
        self.comboBox_scanTriggerSelect = QtWidgets.QComboBox(self.widget_scan_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_scanTriggerSelect.sizePolicy().hasHeightForWidth())
        self.comboBox_scanTriggerSelect.setSizePolicy(sizePolicy)
        self.comboBox_scanTriggerSelect.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_scanTriggerSelect.setObjectName("comboBox_scanTriggerSelect")
        self.gridLayout_7.addWidget(self.comboBox_scanTriggerSelect, 1, 0, 1, 1)
        self.checkBox_scanUseAllTracks = QtWidgets.QCheckBox(self.widget_scan_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_scanUseAllTracks.sizePolicy().hasHeightForWidth())
        self.checkBox_scanUseAllTracks.setSizePolicy(sizePolicy)
        self.checkBox_scanUseAllTracks.setObjectName("checkBox_scanUseAllTracks")
        self.gridLayout_7.addWidget(self.checkBox_scanUseAllTracks, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_7)
        self.scan_trigger_vert_layout = QtWidgets.QVBoxLayout()
        self.scan_trigger_vert_layout.setObjectName("scan_trigger_vert_layout")
        self.widget_scan_trigger_place_holder = QtWidgets.QWidget(self.widget_scan_trigger)
        self.widget_scan_trigger_place_holder.setObjectName("widget_scan_trigger_place_holder")
        self.scan_trigger_vert_layout.addWidget(self.widget_scan_trigger_place_holder)
        self.verticalLayout_9.addLayout(self.scan_trigger_vert_layout)
        self.verticalLayout_10.addWidget(self.widget_scan_trigger)
        self.tabWidget.addTab(self.tab_scan_trigger, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.trigger_tab_widget)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.pushButton_config_pulse_pattern = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_config_pulse_pattern.setObjectName("pushButton_config_pulse_pattern")
        self.verticalLayout.addWidget(self.pushButton_config_pulse_pattern)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pushButton_conf_pre_post_tr_meas = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_conf_pre_post_tr_meas.setObjectName("pushButton_conf_pre_post_tr_meas")
        self.verticalLayout.addWidget(self.pushButton_conf_pre_post_tr_meas)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.pushButton_con_outbits = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_con_outbits.setObjectName("pushButton_con_outbits")
        self.verticalLayout.addWidget(self.pushButton_con_outbits)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.commonSequencerSettings = QtWidgets.QWidget(self.centralwidget)
        self.commonSequencerSettings.setObjectName("commonSequencerSettings")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.commonSequencerSettings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabwidget = QtWidgets.QTabWidget(self.commonSequencerSettings)
        self.tabwidget.setMinimumSize(QtCore.QSize(0, 400))
        self.tabwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabwidget.setObjectName("tabwidget")
        self.seqComSet = QtWidgets.QWidget()
        self.seqComSet.setObjectName("seqComSet")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.seqComSet)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_4.addItem(spacerItem, 16, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.seqComSet)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 350))
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 410, 470))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_nOfScans_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_nOfScans_set.setObjectName("label_nOfScans_set")
        self.gridLayout_8.addWidget(self.label_nOfScans_set, 13, 2, 1, 1)
        self.label_kepco_step = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_kepco_step.setObjectName("label_kepco_step")
        self.gridLayout_8.addWidget(self.label_kepco_step, 9, 3, 1, 1)
        self.label_nOfScans = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_nOfScans.setObjectName("label_nOfScans")
        self.gridLayout_8.addWidget(self.label_nOfScans, 13, 0, 1, 1)
        self.spinBox_nOfSteps = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_nOfSteps.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spinBox_nOfSteps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_nOfSteps.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nOfSteps.setKeyboardTracking(False)
        self.spinBox_nOfSteps.setMaximum(100000000)
        self.spinBox_nOfSteps.setObjectName("spinBox_nOfSteps")
        self.gridLayout_8.addWidget(self.spinBox_nOfSteps, 12, 1, 1, 1)
        self.label_nOfSteps = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_nOfSteps.setObjectName("label_nOfSteps")
        self.gridLayout_8.addWidget(self.label_nOfSteps, 12, 0, 1, 1)
        self.label_nOfSteps_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_nOfSteps_set.setObjectName("label_nOfSteps_set")
        self.gridLayout_8.addWidget(self.label_nOfSteps_set, 12, 2, 1, 1)
        self.spinBox_nOfScans = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_nOfScans.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spinBox_nOfScans.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_nOfScans.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nOfScans.setKeyboardTracking(False)
        self.spinBox_nOfScans.setMaximum(10000000)
        self.spinBox_nOfScans.setObjectName("spinBox_nOfScans")
        self.gridLayout_8.addWidget(self.spinBox_nOfScans, 13, 1, 1, 1)
        self.label_invertScan = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_invertScan.setObjectName("label_invertScan")
        self.gridLayout_8.addWidget(self.label_invertScan, 14, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 15, 2, 1, 1)
        self.comboBox_postAccOffsetVoltControl = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_postAccOffsetVoltControl.setObjectName("comboBox_postAccOffsetVoltControl")
        self.comboBox_postAccOffsetVoltControl.addItem("")
        self.comboBox_postAccOffsetVoltControl.addItem("")
        self.comboBox_postAccOffsetVoltControl.addItem("")
        self.comboBox_postAccOffsetVoltControl.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_postAccOffsetVoltControl, 15, 1, 1, 1)
        self.label_postAccOffsetVolt = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_postAccOffsetVolt.setObjectName("label_postAccOffsetVolt")
        self.gridLayout_8.addWidget(self.label_postAccOffsetVolt, 16, 0, 1, 1)
        self.label_invertScan_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_invertScan_set.setObjectName("label_invertScan_set")
        self.gridLayout_8.addWidget(self.label_invertScan_set, 14, 2, 1, 1)
        self.doubleSpinBox_postAccOffsetVolt = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_postAccOffsetVolt.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_postAccOffsetVolt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_postAccOffsetVolt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_postAccOffsetVolt.setKeyboardTracking(False)
        self.doubleSpinBox_postAccOffsetVolt.setMinimum(-10000.0)
        self.doubleSpinBox_postAccOffsetVolt.setMaximum(10000.0)
        self.doubleSpinBox_postAccOffsetVolt.setObjectName("doubleSpinBox_postAccOffsetVolt")
        self.gridLayout_8.addWidget(self.doubleSpinBox_postAccOffsetVolt, 16, 1, 1, 1)
        self.checkBox_invertScan = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_invertScan.setText("")
        self.checkBox_invertScan.setObjectName("checkBox_invertScan")
        self.gridLayout_8.addWidget(self.checkBox_invertScan, 14, 1, 1, 1)
        self.label_postAccOffsetVoltControl_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_postAccOffsetVoltControl_set.setObjectName("label_postAccOffsetVoltControl_set")
        self.gridLayout_8.addWidget(self.label_postAccOffsetVoltControl_set, 15, 3, 1, 1)
        self.label_postAccOffsetVoltControl = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_postAccOffsetVoltControl.setObjectName("label_postAccOffsetVoltControl")
        self.gridLayout_8.addWidget(self.label_postAccOffsetVoltControl, 15, 0, 1, 1)
        self.label_colDirTrue = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_colDirTrue.setObjectName("label_colDirTrue")
        self.gridLayout_8.addWidget(self.label_colDirTrue, 18, 0, 1, 1)
        self.lineEdit_activePmtList = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_activePmtList.sizePolicy().hasHeightForWidth())
        self.lineEdit_activePmtList.setSizePolicy(sizePolicy)
        self.lineEdit_activePmtList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_activePmtList.setText("")
        self.lineEdit_activePmtList.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_activePmtList.setObjectName("lineEdit_activePmtList")
        self.gridLayout_8.addWidget(self.lineEdit_activePmtList, 17, 1, 1, 1)
        self.label_activePmtList_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_activePmtList_set.setObjectName("label_activePmtList_set")
        self.gridLayout_8.addWidget(self.label_activePmtList_set, 17, 2, 1, 1)
        self.pushButton_postAccOffsetVolt = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_postAccOffsetVolt.setObjectName("pushButton_postAccOffsetVolt")
        self.gridLayout_8.addWidget(self.pushButton_postAccOffsetVolt, 16, 3, 1, 1)
        self.label_activePmtList = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_activePmtList.setObjectName("label_activePmtList")
        self.gridLayout_8.addWidget(self.label_activePmtList, 17, 0, 1, 1)
        self.checkBox_colDirTrue = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_colDirTrue.setText("")
        self.checkBox_colDirTrue.setObjectName("checkBox_colDirTrue")
        self.gridLayout_8.addWidget(self.checkBox_colDirTrue, 18, 1, 1, 1)
        self.label_postAccOffsetVolt_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_postAccOffsetVolt_set.setObjectName("label_postAccOffsetVolt_set")
        self.gridLayout_8.addWidget(self.label_postAccOffsetVolt_set, 16, 2, 1, 1)
        self.label_colDirTrue_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_colDirTrue_set.setObjectName("label_colDirTrue_set")
        self.gridLayout_8.addWidget(self.label_colDirTrue_set, 18, 2, 1, 1)
        self.comboBox_scanDevClass = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_scanDevClass.setObjectName("comboBox_scanDevClass")
        self.gridLayout_8.addWidget(self.comboBox_scanDevClass, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 2, 0, 1, 1)
        self.comboBox_scanDev_type = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_scanDev_type.setObjectName("comboBox_scanDev_type")
        self.gridLayout_8.addWidget(self.comboBox_scanDev_type, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 1, 0, 1, 1)
        self.label_kepco_start = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_kepco_start.setObjectName("label_kepco_start")
        self.gridLayout_8.addWidget(self.label_kepco_start, 7, 3, 1, 1)
        self.label_dacStartV = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_dacStartV.setObjectName("label_dacStartV")
        self.gridLayout_8.addWidget(self.label_dacStartV, 7, 0, 1, 1)
        self.comboBox_scanDev_name = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_scanDev_name.setObjectName("comboBox_scanDev_name")
        self.gridLayout_8.addWidget(self.comboBox_scanDev_name, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_dacStartV_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_dacStartV_set.setObjectName("label_dacStartV_set")
        self.gridLayout_8.addWidget(self.label_dacStartV_set, 7, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 5, 0, 1, 1)
        self.doubleSpinBox_scanDevStart = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_scanDevStart.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_scanDevStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevStart.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevStart.setKeyboardTracking(False)
        self.doubleSpinBox_scanDevStart.setDecimals(8)
        self.doubleSpinBox_scanDevStart.setMinimum(-10.0)
        self.doubleSpinBox_scanDevStart.setMaximum(10.0)
        self.doubleSpinBox_scanDevStart.setSingleStep(0.01)
        self.doubleSpinBox_scanDevStart.setObjectName("doubleSpinBox_scanDevStart")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevStart, 7, 1, 1, 1)
        self.doubleSpinBox_scanDev_timeout_s = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_scanDev_timeout_s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDev_timeout_s.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDev_timeout_s.setDecimals(3)
        self.doubleSpinBox_scanDev_timeout_s.setMaximum(1e+24)
        self.doubleSpinBox_scanDev_timeout_s.setObjectName("doubleSpinBox_scanDev_timeout_s")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDev_timeout_s, 5, 1, 1, 1)
        self.label_dacStopV_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_dacStopV_set.setObjectName("label_dacStopV_set")
        self.gridLayout_8.addWidget(self.label_dacStopV_set, 8, 2, 1, 1)
        self.doubleSpinBox_scanDevStop = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_scanDevStop.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_scanDevStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevStop.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevStop.setKeyboardTracking(False)
        self.doubleSpinBox_scanDevStop.setDecimals(8)
        self.doubleSpinBox_scanDevStop.setMinimum(-10.0)
        self.doubleSpinBox_scanDevStop.setMaximum(10.0)
        self.doubleSpinBox_scanDevStop.setSingleStep(0.01)
        self.doubleSpinBox_scanDevStop.setObjectName("doubleSpinBox_scanDevStop")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevStop, 8, 1, 1, 1)
        self.label_dacStopV = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_dacStopV.setObjectName("label_dacStopV")
        self.gridLayout_8.addWidget(self.label_dacStopV, 8, 0, 1, 1)
        self.label_dacStepSizeV_set = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_dacStepSizeV_set.setObjectName("label_dacStepSizeV_set")
        self.gridLayout_8.addWidget(self.label_dacStepSizeV_set, 9, 2, 1, 1)
        self.doubleSpinBox_scanDevStepSize = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_scanDevStepSize.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_scanDevStepSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevStepSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevStepSize.setKeyboardTracking(False)
        self.doubleSpinBox_scanDevStepSize.setDecimals(8)
        self.doubleSpinBox_scanDevStepSize.setMinimum(-10.0)
        self.doubleSpinBox_scanDevStepSize.setMaximum(10.0)
        self.doubleSpinBox_scanDevStepSize.setSingleStep(0.01)
        self.doubleSpinBox_scanDevStepSize.setObjectName("doubleSpinBox_scanDevStepSize")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevStepSize, 9, 1, 1, 1)
        self.label_kepco_stop = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_kepco_stop.setObjectName("label_kepco_stop")
        self.gridLayout_8.addWidget(self.label_kepco_stop, 8, 3, 1, 1)
        self.label_dacStepSizeV = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_dacStepSizeV.setObjectName("label_dacStepSizeV")
        self.gridLayout_8.addWidget(self.label_dacStepSizeV, 9, 0, 1, 1)
        self.doubleSpinBox_scanDevPreScan = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_scanDevPreScan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevPreScan.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevPreScan.setDecimals(8)
        self.doubleSpinBox_scanDevPreScan.setMinimum(-1e+32)
        self.doubleSpinBox_scanDevPreScan.setMaximum(1e+39)
        self.doubleSpinBox_scanDevPreScan.setObjectName("doubleSpinBox_scanDevPreScan")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevPreScan, 10, 1, 1, 1)
        self.checkBox_scanDev_setPreScan = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_scanDev_setPreScan.setObjectName("checkBox_scanDev_setPreScan")
        self.gridLayout_8.addWidget(self.checkBox_scanDev_setPreScan, 10, 2, 1, 1)
        self.pushButton_scanDev_pre_sc_copy_from_start = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_scanDev_pre_sc_copy_from_start.setObjectName("pushButton_scanDev_pre_sc_copy_from_start")
        self.gridLayout_8.addWidget(self.pushButton_scanDev_pre_sc_copy_from_start, 10, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 10, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 11, 0, 1, 1)
        self.doubleSpinBox_scanDevPostScan = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_scanDevPostScan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevPostScan.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevPostScan.setDecimals(8)
        self.doubleSpinBox_scanDevPostScan.setMinimum(-1e+23)
        self.doubleSpinBox_scanDevPostScan.setMaximum(1e+29)
        self.doubleSpinBox_scanDevPostScan.setObjectName("doubleSpinBox_scanDevPostScan")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevPostScan, 11, 1, 1, 1)
        self.checkBox_scanDev_setPostScan = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_scanDev_setPostScan.setObjectName("checkBox_scanDev_setPostScan")
        self.gridLayout_8.addWidget(self.checkBox_scanDev_setPostScan, 11, 2, 1, 1)
        self.pushButton_scanDev_post_ssc_copy_stop = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_scanDev_post_ssc_copy_stop.setObjectName("pushButton_scanDev_post_ssc_copy_stop")
        self.gridLayout_8.addWidget(self.pushButton_scanDev_post_ssc_copy_stop, 11, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_scanDev_unit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_scanDev_unit.setObjectName("label_scanDev_unit")
        self.gridLayout_8.addWidget(self.label_scanDev_unit, 4, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea, 2, 0, 2, 4)
        self.tabwidget.addTab(self.seqComSet, "")
        self.advancedSeqSettings = QtWidgets.QWidget()
        self.advancedSeqSettings.setObjectName("advancedSeqSettings")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.advancedSeqSettings)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.doubleSpinBox_waitAfterReset_muS = QtWidgets.QDoubleSpinBox(self.advancedSeqSettings)
        self.doubleSpinBox_waitAfterReset_muS.setFrame(True)
        self.doubleSpinBox_waitAfterReset_muS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_waitAfterReset_muS.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_waitAfterReset_muS.setKeyboardTracking(False)
        self.doubleSpinBox_waitAfterReset_muS.setDecimals(3)
        self.doubleSpinBox_waitAfterReset_muS.setMaximum(4200000.0)
        self.doubleSpinBox_waitAfterReset_muS.setSingleStep(0.5)
        self.doubleSpinBox_waitAfterReset_muS.setObjectName("doubleSpinBox_waitAfterReset_muS")
        self.gridLayout_5.addWidget(self.doubleSpinBox_waitAfterReset_muS, 2, 1, 1, 1)
        self.label_waitForKepco_muS = QtWidgets.QLabel(self.advancedSeqSettings)
        self.label_waitForKepco_muS.setObjectName("label_waitForKepco_muS")
        self.gridLayout_5.addWidget(self.label_waitForKepco_muS, 1, 0, 1, 1)
        self.doubleSpinBox_waitForKepco_muS = QtWidgets.QDoubleSpinBox(self.advancedSeqSettings)
        self.doubleSpinBox_waitForKepco_muS.setFrame(True)
        self.doubleSpinBox_waitForKepco_muS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_waitForKepco_muS.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_waitForKepco_muS.setKeyboardTracking(False)
        self.doubleSpinBox_waitForKepco_muS.setDecimals(3)
        self.doubleSpinBox_waitForKepco_muS.setMaximum(4200000.0)
        self.doubleSpinBox_waitForKepco_muS.setSingleStep(0.5)
        self.doubleSpinBox_waitForKepco_muS.setObjectName("doubleSpinBox_waitForKepco_muS")
        self.gridLayout_5.addWidget(self.doubleSpinBox_waitForKepco_muS, 1, 1, 1, 1)
        self.label_waitAfterReset_muS = QtWidgets.QLabel(self.advancedSeqSettings)
        self.label_waitAfterReset_muS.setObjectName("label_waitAfterReset_muS")
        self.gridLayout_5.addWidget(self.label_waitAfterReset_muS, 2, 0, 1, 1)
        self.label_waitForKepco_muS_set = QtWidgets.QLabel(self.advancedSeqSettings)
        self.label_waitForKepco_muS_set.setObjectName("label_waitForKepco_muS_set")
        self.gridLayout_5.addWidget(self.label_waitForKepco_muS_set, 1, 2, 1, 1)
        self.label_waitAfterReset_muS_set = QtWidgets.QLabel(self.advancedSeqSettings)
        self.label_waitAfterReset_muS_set.setObjectName("label_waitAfterReset_muS_set")
        self.gridLayout_5.addWidget(self.label_waitAfterReset_muS_set, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.advancedSeqSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.advancedSeqSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.advancedSeqSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabwidget.addTab(self.advancedSeqSettings, "")
        self.verticalLayout_4.addWidget(self.tabwidget)
        self.gridWidgetButtons = QtWidgets.QWidget(self.commonSequencerSettings)
        self.gridWidgetButtons.setMinimumSize(QtCore.QSize(366, 50))
        self.gridWidgetButtons.setObjectName("gridWidgetButtons")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridWidgetButtons)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonResetToDefault = QtWidgets.QPushButton(self.gridWidgetButtons)
        self.pushButtonResetToDefault.setObjectName("pushButtonResetToDefault")
        self.gridLayout_3.addWidget(self.pushButtonResetToDefault, 0, 0, 1, 1)
        self.pushButton_confirm = QtWidgets.QPushButton(self.gridWidgetButtons)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.gridLayout_3.addWidget(self.pushButton_confirm, 0, 1, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(self.gridWidgetButtons)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_3.addWidget(self.pushButton_cancel, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.gridWidgetButtons)
        self.verticalLayout.addWidget(self.commonSequencerSettings)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindowTrackPars.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowTrackPars)
        self.statusbar.setObjectName("statusbar")
        MainWindowTrackPars.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowTrackPars)
        self.tabWidget.setCurrentIndex(0)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowTrackPars)
        MainWindowTrackPars.setTabOrder(self.tabWidget, self.comboBox_triggerSelect)
        MainWindowTrackPars.setTabOrder(self.comboBox_triggerSelect, self.checkBox_UseAllTracks)
        MainWindowTrackPars.setTabOrder(self.checkBox_UseAllTracks, self.pushButton_config_pulse_pattern)
        MainWindowTrackPars.setTabOrder(self.pushButton_config_pulse_pattern, self.pushButton_conf_pre_post_tr_meas)
        MainWindowTrackPars.setTabOrder(self.pushButton_conf_pre_post_tr_meas, self.pushButton_con_outbits)
        MainWindowTrackPars.setTabOrder(self.pushButton_con_outbits, self.tabwidget)
        MainWindowTrackPars.setTabOrder(self.tabwidget, self.scrollArea)
        MainWindowTrackPars.setTabOrder(self.scrollArea, self.comboBox_scanDevClass)
        MainWindowTrackPars.setTabOrder(self.comboBox_scanDevClass, self.comboBox_scanDev_type)
        MainWindowTrackPars.setTabOrder(self.comboBox_scanDev_type, self.comboBox_scanDev_name)
        MainWindowTrackPars.setTabOrder(self.comboBox_scanDev_name, self.doubleSpinBox_scanDev_timeout_s)
        MainWindowTrackPars.setTabOrder(self.doubleSpinBox_scanDev_timeout_s, self.doubleSpinBox_scanDevStart)
        MainWindowTrackPars.setTabOrder(self.doubleSpinBox_scanDevStart, self.doubleSpinBox_scanDevStop)
        MainWindowTrackPars.setTabOrder(self.doubleSpinBox_scanDevStop, self.doubleSpinBox_scanDevStepSize)
        MainWindowTrackPars.setTabOrder(self.doubleSpinBox_scanDevStepSize, self.doubleSpinBox_scanDevPreScan)
        MainWindowTrackPars.setTabOrder(self.doubleSpinBox_scanDevPreScan, self.checkBox_scanDev_setPreScan)
        MainWindowTrackPars.setTabOrder(self.checkBox_scanDev_setPreScan, self.pushButton_scanDev_pre_sc_copy_from_start)
        MainWindowTrackPars.setTabOrder(self.pushButton_scanDev_pre_sc_copy_from_start, self.doubleSpinBox_scanDevPostScan)
        MainWindowTrackPars.setTabOrder(self.doubleSpinBox_scanDevPostScan, self.checkBox_scanDev_setPostScan)
        MainWindowTrackPars.setTabOrder(self.checkBox_scanDev_setPostScan, self.pushButton_scanDev_post_ssc_copy_stop)
        MainWindowTrackPars.setTabOrder(self.pushButton_scanDev_post_ssc_copy_stop, self.spinBox_nOfSteps)
        MainWindowTrackPars.setTabOrder(self.spinBox_nOfSteps, self.spinBox_nOfScans)
        MainWindowTrackPars.setTabOrder(self.spinBox_nOfScans, self.checkBox_invertScan)
        MainWindowTrackPars.setTabOrder(self.checkBox_invertScan, self.comboBox_postAccOffsetVoltControl)
        MainWindowTrackPars.setTabOrder(self.comboBox_postAccOffsetVoltControl, self.doubleSpinBox_postAccOffsetVolt)
        MainWindowTrackPars.setTabOrder(self.doubleSpinBox_postAccOffsetVolt, self.pushButton_postAccOffsetVolt)
        MainWindowTrackPars.setTabOrder(self.pushButton_postAccOffsetVolt, self.lineEdit_activePmtList)
        MainWindowTrackPars.setTabOrder(self.lineEdit_activePmtList, self.checkBox_colDirTrue)
        MainWindowTrackPars.setTabOrder(self.checkBox_colDirTrue, self.pushButtonResetToDefault)
        MainWindowTrackPars.setTabOrder(self.pushButtonResetToDefault, self.pushButton_confirm)
        MainWindowTrackPars.setTabOrder(self.pushButton_confirm, self.pushButton_cancel)
        MainWindowTrackPars.setTabOrder(self.pushButton_cancel, self.doubleSpinBox_waitForKepco_muS)
        MainWindowTrackPars.setTabOrder(self.doubleSpinBox_waitForKepco_muS, self.doubleSpinBox_waitAfterReset_muS)
        MainWindowTrackPars.setTabOrder(self.doubleSpinBox_waitAfterReset_muS, self.checkBox_stepUseAllTracks)
        MainWindowTrackPars.setTabOrder(self.checkBox_stepUseAllTracks, self.checkBox_scanUseAllTracks)
        MainWindowTrackPars.setTabOrder(self.checkBox_scanUseAllTracks, self.comboBox_stepTriggerSelect)
        MainWindowTrackPars.setTabOrder(self.comboBox_stepTriggerSelect, self.comboBox_scanTriggerSelect)

    def retranslateUi(self, MainWindowTrackPars):
        _translate = QtCore.QCoreApplication.translate
        MainWindowTrackPars.setWindowTitle(_translate("MainWindowTrackPars", "track parameters"))
        self.label_descriptionTrigger.setText(_translate("MainWindowTrackPars", "Standard trigger. Triggers measurements per bunch(TRS) or step(CS)"))
        self.label_Trigger.setText(_translate("MainWindowTrackPars", "trigger:"))
        self.checkBox_UseAllTracks.setText(_translate("MainWindowTrackPars", "use for all tracks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_trigger), _translate("MainWindowTrackPars", "meas Trigger"))
        self.label_descriptionStepTrigger.setText(_translate("MainWindowTrackPars", "Advanced trigger. Used to trigger next step. Usefull for laser scanning!"))
        self.label_stepTrigger.setText(_translate("MainWindowTrackPars", "step trigger:"))
        self.checkBox_stepUseAllTracks.setText(_translate("MainWindowTrackPars", "use for all tracks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_step_trigger), _translate("MainWindowTrackPars", "step Trigger"))
        self.label_9.setText(_translate("MainWindowTrackPars", "Advanced trigger. Used to trigger next scan."))
        self.label_scanTrigger.setText(_translate("MainWindowTrackPars", "scan trigger:"))
        self.checkBox_scanUseAllTracks.setText(_translate("MainWindowTrackPars", "use for all tracks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scan_trigger), _translate("MainWindowTrackPars", "scan Trigger"))
        self.pushButton_config_pulse_pattern.setText(_translate("MainWindowTrackPars", "configure pulse pattern"))
        self.pushButton_conf_pre_post_tr_meas.setText(_translate("MainWindowTrackPars", "configure dmm/triton measurements"))
        self.pushButton_con_outbits.setText(_translate("MainWindowTrackPars", "configure outbits"))
        self.label_5.setText(_translate("MainWindowTrackPars", "Set Value"))
        self.label_7.setText(_translate("MainWindowTrackPars", "DAC * 50"))
        self.label_4.setText(_translate("MainWindowTrackPars", "User Input"))
        self.label_3.setText(_translate("MainWindowTrackPars", "Parameter"))
        self.label_nOfScans_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_kepco_step.setText(_translate("MainWindowTrackPars", "None"))
        self.label_nOfScans.setText(_translate("MainWindowTrackPars", "number of Scans"))
        self.label_nOfSteps.setText(_translate("MainWindowTrackPars", "number of steps"))
        self.label_nOfSteps_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_invertScan.setText(_translate("MainWindowTrackPars", "invert scan direction"))
        self.label_11.setText(_translate("MainWindowTrackPars", "readback\n"
"Voltage:"))
        self.comboBox_postAccOffsetVoltControl.setItemText(0, _translate("MainWindowTrackPars", "Kepco"))
        self.comboBox_postAccOffsetVoltControl.setItemText(1, _translate("MainWindowTrackPars", "Heinzinger1"))
        self.comboBox_postAccOffsetVoltControl.setItemText(2, _translate("MainWindowTrackPars", "Heinzinger2"))
        self.comboBox_postAccOffsetVoltControl.setItemText(3, _translate("MainWindowTrackPars", "Heinzinger3"))
        self.label_postAccOffsetVolt.setText(_translate("MainWindowTrackPars", "post Acceleration \n"
"power supply voltage [V]"))
        self.label_invertScan_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_postAccOffsetVoltControl_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_postAccOffsetVoltControl.setText(_translate("MainWindowTrackPars", "post Acceleration \n"
"power supply"))
        self.label_colDirTrue.setText(_translate("MainWindowTrackPars", "measured collinear?"))
        self.label_activePmtList_set.setText(_translate("MainWindowTrackPars", "None"))
        self.pushButton_postAccOffsetVolt.setText(_translate("MainWindowTrackPars", "set volt"))
        self.label_activePmtList.setText(_translate("MainWindowTrackPars", "active PMT List"))
        self.label_postAccOffsetVolt_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_colDirTrue_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_8.setText(_translate("MainWindowTrackPars", "scan device type"))
        self.label.setText(_translate("MainWindowTrackPars", "scan device class"))
        self.label_kepco_start.setText(_translate("MainWindowTrackPars", "None"))
        self.label_dacStartV.setText(_translate("MainWindowTrackPars", "scan dev start"))
        self.label_10.setText(_translate("MainWindowTrackPars", "scan device name"))
        self.label_dacStartV_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_12.setText(_translate("MainWindowTrackPars", "scan device timeout [s]"))
        self.label_dacStopV_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_dacStopV.setText(_translate("MainWindowTrackPars", "scan dev stop"))
        self.label_dacStepSizeV_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_kepco_stop.setText(_translate("MainWindowTrackPars", "None"))
        self.label_dacStepSizeV.setText(_translate("MainWindowTrackPars", "scan dev step size"))
        self.checkBox_scanDev_setPreScan.setText(_translate("MainWindowTrackPars", "Set"))
        self.pushButton_scanDev_pre_sc_copy_from_start.setText(_translate("MainWindowTrackPars", "copy start"))
        self.label_14.setText(_translate("MainWindowTrackPars", "scan dev pre scan value"))
        self.label_15.setText(_translate("MainWindowTrackPars", "scan dev post scan value"))
        self.checkBox_scanDev_setPostScan.setText(_translate("MainWindowTrackPars", "Set"))
        self.pushButton_scanDev_post_ssc_copy_stop.setText(_translate("MainWindowTrackPars", "copy stop"))
        self.label_16.setText(_translate("MainWindowTrackPars", "scan device unit"))
        self.label_scanDev_unit.setText(_translate("MainWindowTrackPars", "not defined"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.seqComSet), _translate("MainWindowTrackPars", "common Sequencer Settings"))
        self.label_waitForKepco_muS.setText(_translate("MainWindowTrackPars", "wait after each voltage set [µs]"))
        self.label_waitAfterReset_muS.setText(_translate("MainWindowTrackPars", "wait after voltage reset [µs]"))
        self.label_waitForKepco_muS_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_waitAfterReset_muS_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_6.setText(_translate("MainWindowTrackPars", "user input"))
        self.label_13.setText(_translate("MainWindowTrackPars", "set value"))
        self.label_2.setText(_translate("MainWindowTrackPars", "parameter"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.advancedSeqSettings), _translate("MainWindowTrackPars", "advanced Settings"))
        self.pushButtonResetToDefault.setText(_translate("MainWindowTrackPars", "reset to default"))
        self.pushButton_confirm.setText(_translate("MainWindowTrackPars", "confirm"))
        self.pushButton_cancel.setText(_translate("MainWindowTrackPars", "cancel"))

