# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_TrackPar_Wide.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowTrackPars(object):
    def setupUi(self, MainWindowTrackPars):
        MainWindowTrackPars.setObjectName("MainWindowTrackPars")
        MainWindowTrackPars.resize(944, 635)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowTrackPars.sizePolicy().hasHeightForWidth())
        MainWindowTrackPars.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/track_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowTrackPars.setWindowIcon(icon)
        MainWindowTrackPars.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindowTrackPars)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_base = QtWidgets.QVBoxLayout()
        self.verticalLayout_base.setObjectName("verticalLayout_base")
        self.horizontalLayout_base = QtWidgets.QHBoxLayout()
        self.horizontalLayout_base.setObjectName("horizontalLayout_base")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.specificSequencerSettings = QtWidgets.QWidget(self.centralwidget)
        self.specificSequencerSettings.setObjectName("specificSequencerSettings")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.specificSequencerSettings)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout.addWidget(self.specificSequencerSettings)
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout.addWidget(self.line_1)
        self.trigger_tab_widget = QtWidgets.QWidget(self.centralwidget)
        self.trigger_tab_widget.setEnabled(True)
        self.trigger_tab_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.trigger_tab_widget.setBaseSize(QtCore.QSize(0, 0))
        self.trigger_tab_widget.setObjectName("trigger_tab_widget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.trigger_tab_widget)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tabWidget = QtWidgets.QTabWidget(self.trigger_tab_widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_trigger = QtWidgets.QWidget()
        self.tab_trigger.setObjectName("tab_trigger")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_trigger)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_descriptionTrigger = QtWidgets.QLabel(self.tab_trigger)
        self.label_descriptionTrigger.setObjectName("label_descriptionTrigger")
        self.verticalLayout_18.addWidget(self.label_descriptionTrigger)
        self.widget_trigger = QtWidgets.QWidget(self.tab_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_trigger.sizePolicy().hasHeightForWidth())
        self.widget_trigger.setSizePolicy(sizePolicy)
        self.widget_trigger.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_trigger.setObjectName("widget_trigger")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_trigger)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_Trigger = QtWidgets.QLabel(self.widget_trigger)
        self.label_Trigger.setObjectName("label_Trigger")
        self.gridLayout_14.addWidget(self.label_Trigger, 0, 0, 1, 1)
        self.comboBox_triggerSelect = QtWidgets.QComboBox(self.widget_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_triggerSelect.sizePolicy().hasHeightForWidth())
        self.comboBox_triggerSelect.setSizePolicy(sizePolicy)
        self.comboBox_triggerSelect.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_triggerSelect.setObjectName("comboBox_triggerSelect")
        self.gridLayout_14.addWidget(self.comboBox_triggerSelect, 1, 0, 1, 1)
        self.checkBox_UseAllTracks = QtWidgets.QCheckBox(self.widget_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_UseAllTracks.sizePolicy().hasHeightForWidth())
        self.checkBox_UseAllTracks.setSizePolicy(sizePolicy)
        self.checkBox_UseAllTracks.setObjectName("checkBox_UseAllTracks")
        self.gridLayout_14.addWidget(self.checkBox_UseAllTracks, 1, 1, 1, 1)
        self.verticalLayout_19.addLayout(self.gridLayout_14)
        self.trigger_vert_layout = QtWidgets.QVBoxLayout()
        self.trigger_vert_layout.setObjectName("trigger_vert_layout")
        self.widget_trigger_place_holder = QtWidgets.QWidget(self.widget_trigger)
        self.widget_trigger_place_holder.setObjectName("widget_trigger_place_holder")
        self.trigger_vert_layout.addWidget(self.widget_trigger_place_holder)
        self.verticalLayout_19.addLayout(self.trigger_vert_layout)
        self.verticalLayout_18.addWidget(self.widget_trigger)
        self.tabWidget.addTab(self.tab_trigger, "")
        self.tab_step_trigger = QtWidgets.QWidget()
        self.tab_step_trigger.setObjectName("tab_step_trigger")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_step_trigger)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_descriptionStepTrigger = QtWidgets.QLabel(self.tab_step_trigger)
        self.label_descriptionStepTrigger.setObjectName("label_descriptionStepTrigger")
        self.verticalLayout_20.addWidget(self.label_descriptionStepTrigger)
        self.widget_step_trigger = QtWidgets.QWidget(self.tab_step_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_step_trigger.sizePolicy().hasHeightForWidth())
        self.widget_step_trigger.setSizePolicy(sizePolicy)
        self.widget_step_trigger.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_step_trigger.setObjectName("widget_step_trigger")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_step_trigger)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_stepTrigger = QtWidgets.QLabel(self.widget_step_trigger)
        self.label_stepTrigger.setObjectName("label_stepTrigger")
        self.gridLayout_15.addWidget(self.label_stepTrigger, 0, 0, 1, 1)
        self.checkBox_stepUseAllTracks = QtWidgets.QCheckBox(self.widget_step_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_stepUseAllTracks.sizePolicy().hasHeightForWidth())
        self.checkBox_stepUseAllTracks.setSizePolicy(sizePolicy)
        self.checkBox_stepUseAllTracks.setObjectName("checkBox_stepUseAllTracks")
        self.gridLayout_15.addWidget(self.checkBox_stepUseAllTracks, 1, 1, 1, 1)
        self.comboBox_stepTriggerSelect = QtWidgets.QComboBox(self.widget_step_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_stepTriggerSelect.sizePolicy().hasHeightForWidth())
        self.comboBox_stepTriggerSelect.setSizePolicy(sizePolicy)
        self.comboBox_stepTriggerSelect.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_stepTriggerSelect.setObjectName("comboBox_stepTriggerSelect")
        self.gridLayout_15.addWidget(self.comboBox_stepTriggerSelect, 1, 0, 1, 1)
        self.verticalLayout_21.addLayout(self.gridLayout_15)
        self.step_trigger_vert_layout = QtWidgets.QVBoxLayout()
        self.step_trigger_vert_layout.setObjectName("step_trigger_vert_layout")
        self.widget_step_trigger_place_holder = QtWidgets.QWidget(self.widget_step_trigger)
        self.widget_step_trigger_place_holder.setObjectName("widget_step_trigger_place_holder")
        self.step_trigger_vert_layout.addWidget(self.widget_step_trigger_place_holder)
        self.verticalLayout_21.addLayout(self.step_trigger_vert_layout)
        self.verticalLayout_20.addWidget(self.widget_step_trigger)
        self.tabWidget.addTab(self.tab_step_trigger, "")
        self.tab_scan_trigger = QtWidgets.QWidget()
        self.tab_scan_trigger.setObjectName("tab_scan_trigger")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_scan_trigger)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_18 = QtWidgets.QLabel(self.tab_scan_trigger)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_22.addWidget(self.label_18)
        self.widget_scan_trigger = QtWidgets.QWidget(self.tab_scan_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_scan_trigger.sizePolicy().hasHeightForWidth())
        self.widget_scan_trigger.setSizePolicy(sizePolicy)
        self.widget_scan_trigger.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_scan_trigger.setObjectName("widget_scan_trigger")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_scan_trigger)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_scanTrigger = QtWidgets.QLabel(self.widget_scan_trigger)
        self.label_scanTrigger.setObjectName("label_scanTrigger")
        self.gridLayout_16.addWidget(self.label_scanTrigger, 0, 0, 1, 1)
        self.comboBox_scanTriggerSelect = QtWidgets.QComboBox(self.widget_scan_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_scanTriggerSelect.sizePolicy().hasHeightForWidth())
        self.comboBox_scanTriggerSelect.setSizePolicy(sizePolicy)
        self.comboBox_scanTriggerSelect.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_scanTriggerSelect.setObjectName("comboBox_scanTriggerSelect")
        self.gridLayout_16.addWidget(self.comboBox_scanTriggerSelect, 1, 0, 1, 1)
        self.checkBox_scanUseAllTracks = QtWidgets.QCheckBox(self.widget_scan_trigger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_scanUseAllTracks.sizePolicy().hasHeightForWidth())
        self.checkBox_scanUseAllTracks.setSizePolicy(sizePolicy)
        self.checkBox_scanUseAllTracks.setObjectName("checkBox_scanUseAllTracks")
        self.gridLayout_16.addWidget(self.checkBox_scanUseAllTracks, 1, 1, 1, 1)
        self.verticalLayout_23.addLayout(self.gridLayout_16)
        self.scan_trigger_vert_layout = QtWidgets.QVBoxLayout()
        self.scan_trigger_vert_layout.setObjectName("scan_trigger_vert_layout")
        self.widget_scan_trigger_place_holder = QtWidgets.QWidget(self.widget_scan_trigger)
        self.widget_scan_trigger_place_holder.setObjectName("widget_scan_trigger_place_holder")
        self.scan_trigger_vert_layout.addWidget(self.widget_scan_trigger_place_holder)
        self.verticalLayout_23.addLayout(self.scan_trigger_vert_layout)
        self.verticalLayout_22.addWidget(self.widget_scan_trigger)
        self.tabWidget.addTab(self.tab_scan_trigger, "")
        self.verticalLayout_17.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.trigger_tab_widget)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_24.addWidget(self.line_2)
        self.pushButton_config_pulse_pattern = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_config_pulse_pattern.setObjectName("pushButton_config_pulse_pattern")
        self.verticalLayout_24.addWidget(self.pushButton_config_pulse_pattern)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_24.addWidget(self.line_3)
        self.pushButton_conf_pre_post_tr_meas = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_conf_pre_post_tr_meas.setObjectName("pushButton_conf_pre_post_tr_meas")
        self.verticalLayout_24.addWidget(self.pushButton_conf_pre_post_tr_meas)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_24.addWidget(self.line_4)
        self.pushButton_con_outbits = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_con_outbits.setObjectName("pushButton_con_outbits")
        self.verticalLayout_24.addWidget(self.pushButton_con_outbits)
        self.verticalLayout.addLayout(self.verticalLayout_24)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_base.addLayout(self.verticalLayout)
        self.tabwidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabwidget.setMinimumSize(QtCore.QSize(0, 400))
        self.tabwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabwidget.setObjectName("tabwidget")
        self.seqComSet = QtWidgets.QWidget()
        self.seqComSet.setObjectName("seqComSet")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.seqComSet)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.seqComSet)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 350))
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 432, 491))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.doubleSpinBox_scanDevStepSize = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_scanDevStepSize.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_scanDevStepSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevStepSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevStepSize.setKeyboardTracking(False)
        self.doubleSpinBox_scanDevStepSize.setDecimals(8)
        self.doubleSpinBox_scanDevStepSize.setMinimum(-10.0)
        self.doubleSpinBox_scanDevStepSize.setMaximum(10.0)
        self.doubleSpinBox_scanDevStepSize.setSingleStep(0.01)
        self.doubleSpinBox_scanDevStepSize.setObjectName("doubleSpinBox_scanDevStepSize")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevStepSize, 11, 1, 1, 1)
        self.doubleSpinBox_scanDevPreScan = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_scanDevPreScan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevPreScan.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevPreScan.setDecimals(8)
        self.doubleSpinBox_scanDevPreScan.setMinimum(-1e+32)
        self.doubleSpinBox_scanDevPreScan.setMaximum(1e+39)
        self.doubleSpinBox_scanDevPreScan.setObjectName("doubleSpinBox_scanDevPreScan")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevPreScan, 12, 1, 1, 1)
        self.label_dacStepSizeV = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_dacStepSizeV.setObjectName("label_dacStepSizeV")
        self.gridLayout_8.addWidget(self.label_dacStepSizeV, 11, 0, 1, 1)
        self.label_kepco_stop = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_kepco_stop.setObjectName("label_kepco_stop")
        self.gridLayout_8.addWidget(self.label_kepco_stop, 10, 3, 1, 1)
        self.label_dacStepSizeV_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_dacStepSizeV_set.setObjectName("label_dacStepSizeV_set")
        self.gridLayout_8.addWidget(self.label_dacStepSizeV_set, 11, 2, 1, 1)
        self.pushButton_scanDev_pre_sc_copy_from_start = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_scanDev_pre_sc_copy_from_start.setObjectName("pushButton_scanDev_pre_sc_copy_from_start")
        self.gridLayout_8.addWidget(self.pushButton_scanDev_pre_sc_copy_from_start, 12, 3, 1, 1)
        self.checkBox_scanDev_setPreScan = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_scanDev_setPreScan.setObjectName("checkBox_scanDev_setPreScan")
        self.gridLayout_8.addWidget(self.checkBox_scanDev_setPreScan, 12, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 12, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 13, 0, 1, 1)
        self.doubleSpinBox_scanDevPostScan = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_scanDevPostScan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevPostScan.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevPostScan.setDecimals(8)
        self.doubleSpinBox_scanDevPostScan.setMinimum(-1e+23)
        self.doubleSpinBox_scanDevPostScan.setMaximum(1e+29)
        self.doubleSpinBox_scanDevPostScan.setObjectName("doubleSpinBox_scanDevPostScan")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevPostScan, 13, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 5, 0, 1, 1)
        self.pushButton_scanDev_post_ssc_copy_stop = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_scanDev_post_ssc_copy_stop.setObjectName("pushButton_scanDev_post_ssc_copy_stop")
        self.gridLayout_8.addWidget(self.pushButton_scanDev_post_ssc_copy_stop, 13, 3, 1, 1)
        self.label_scanDev_unit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_scanDev_unit.setObjectName("label_scanDev_unit")
        self.gridLayout_8.addWidget(self.label_scanDev_unit, 5, 1, 1, 1)
        self.checkBox_scanDev_setPostScan = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_scanDev_setPostScan.setObjectName("checkBox_scanDev_setPostScan")
        self.gridLayout_8.addWidget(self.checkBox_scanDev_setPostScan, 13, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_kepco_step = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_kepco_step.setObjectName("label_kepco_step")
        self.gridLayout_8.addWidget(self.label_kepco_step, 11, 3, 1, 1)
        self.label_nOfScans_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_nOfScans_set.setObjectName("label_nOfScans_set")
        self.gridLayout_8.addWidget(self.label_nOfScans_set, 15, 2, 1, 1)
        self.label_nOfSteps = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_nOfSteps.setObjectName("label_nOfSteps")
        self.gridLayout_8.addWidget(self.label_nOfSteps, 14, 0, 1, 1)
        self.spinBox_nOfSteps = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_nOfSteps.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spinBox_nOfSteps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_nOfSteps.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nOfSteps.setKeyboardTracking(False)
        self.spinBox_nOfSteps.setMaximum(100000000)
        self.spinBox_nOfSteps.setObjectName("spinBox_nOfSteps")
        self.gridLayout_8.addWidget(self.spinBox_nOfSteps, 14, 1, 1, 1)
        self.label_nOfSteps_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_nOfSteps_set.setObjectName("label_nOfSteps_set")
        self.gridLayout_8.addWidget(self.label_nOfSteps_set, 14, 2, 1, 1)
        self.label_nOfScans = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_nOfScans.setObjectName("label_nOfScans")
        self.gridLayout_8.addWidget(self.label_nOfScans, 15, 0, 1, 1)
        self.spinBox_nOfScans = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_nOfScans.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spinBox_nOfScans.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_nOfScans.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nOfScans.setKeyboardTracking(False)
        self.spinBox_nOfScans.setMaximum(10000000)
        self.spinBox_nOfScans.setObjectName("spinBox_nOfScans")
        self.gridLayout_8.addWidget(self.spinBox_nOfScans, 15, 1, 1, 1)
        self.comboBox_postAccOffsetVoltControl = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_postAccOffsetVoltControl.setObjectName("comboBox_postAccOffsetVoltControl")
        self.comboBox_postAccOffsetVoltControl.addItem("")
        self.comboBox_postAccOffsetVoltControl.addItem("")
        self.comboBox_postAccOffsetVoltControl.addItem("")
        self.comboBox_postAccOffsetVoltControl.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_postAccOffsetVoltControl, 17, 1, 1, 1)
        self.label_invertScan_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_invertScan_set.setObjectName("label_invertScan_set")
        self.gridLayout_8.addWidget(self.label_invertScan_set, 16, 2, 1, 1)
        self.label_postAccOffsetVolt = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_postAccOffsetVolt.setObjectName("label_postAccOffsetVolt")
        self.gridLayout_8.addWidget(self.label_postAccOffsetVolt, 18, 0, 1, 1)
        self.label_invertScan = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_invertScan.setObjectName("label_invertScan")
        self.gridLayout_8.addWidget(self.label_invertScan, 16, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 17, 2, 1, 1)
        self.label_postAccOffsetVoltControl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_postAccOffsetVoltControl.setObjectName("label_postAccOffsetVoltControl")
        self.gridLayout_8.addWidget(self.label_postAccOffsetVoltControl, 17, 0, 1, 1)
        self.doubleSpinBox_postAccOffsetVolt = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_postAccOffsetVolt.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_postAccOffsetVolt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_postAccOffsetVolt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_postAccOffsetVolt.setKeyboardTracking(False)
        self.doubleSpinBox_postAccOffsetVolt.setMinimum(-10000.0)
        self.doubleSpinBox_postAccOffsetVolt.setMaximum(10000.0)
        self.doubleSpinBox_postAccOffsetVolt.setObjectName("doubleSpinBox_postAccOffsetVolt")
        self.gridLayout_8.addWidget(self.doubleSpinBox_postAccOffsetVolt, 18, 1, 1, 1)
        self.checkBox_invertScan = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_invertScan.setText("")
        self.checkBox_invertScan.setObjectName("checkBox_invertScan")
        self.gridLayout_8.addWidget(self.checkBox_invertScan, 16, 1, 1, 1)
        self.label_postAccOffsetVoltControl_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_postAccOffsetVoltControl_set.setObjectName("label_postAccOffsetVoltControl_set")
        self.gridLayout_8.addWidget(self.label_postAccOffsetVoltControl_set, 17, 3, 1, 1)
        self.label_colDirTrue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_colDirTrue.setObjectName("label_colDirTrue")
        self.gridLayout_8.addWidget(self.label_colDirTrue, 20, 0, 1, 1)
        self.lineEdit_activePmtList = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_activePmtList.sizePolicy().hasHeightForWidth())
        self.lineEdit_activePmtList.setSizePolicy(sizePolicy)
        self.lineEdit_activePmtList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_activePmtList.setText("")
        self.lineEdit_activePmtList.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_activePmtList.setObjectName("lineEdit_activePmtList")
        self.gridLayout_8.addWidget(self.lineEdit_activePmtList, 19, 1, 1, 1)
        self.label_activePmtList_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_activePmtList_set.setObjectName("label_activePmtList_set")
        self.gridLayout_8.addWidget(self.label_activePmtList_set, 19, 2, 1, 1)
        self.pushButton_postAccOffsetVolt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_postAccOffsetVolt.setObjectName("pushButton_postAccOffsetVolt")
        self.gridLayout_8.addWidget(self.pushButton_postAccOffsetVolt, 18, 3, 1, 1)
        self.label_activePmtList = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_activePmtList.setObjectName("label_activePmtList")
        self.gridLayout_8.addWidget(self.label_activePmtList, 19, 0, 1, 1)
        self.comboBox_scanDevClass = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_scanDevClass.setObjectName("comboBox_scanDevClass")
        self.gridLayout_8.addWidget(self.comboBox_scanDevClass, 2, 1, 1, 1)
        self.label_postAccOffsetVolt_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_postAccOffsetVolt_set.setObjectName("label_postAccOffsetVolt_set")
        self.gridLayout_8.addWidget(self.label_postAccOffsetVolt_set, 18, 2, 1, 1)
        self.checkBox_colDirTrue = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_colDirTrue.setText("")
        self.checkBox_colDirTrue.setObjectName("checkBox_colDirTrue")
        self.gridLayout_8.addWidget(self.checkBox_colDirTrue, 20, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 3, 0, 1, 1)
        self.comboBox_scanDev_type = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_scanDev_type.setObjectName("comboBox_scanDev_type")
        self.gridLayout_8.addWidget(self.comboBox_scanDev_type, 3, 1, 1, 1)
        self.label_colDirTrue_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_colDirTrue_set.setObjectName("label_colDirTrue_set")
        self.gridLayout_8.addWidget(self.label_colDirTrue_set, 20, 2, 1, 1)
        self.label_dacStartV = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_dacStartV.setObjectName("label_dacStartV")
        self.gridLayout_8.addWidget(self.label_dacStartV, 9, 0, 1, 1)
        self.comboBox_scanDev_name = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_scanDev_name.setObjectName("comboBox_scanDev_name")
        self.gridLayout_8.addWidget(self.comboBox_scanDev_name, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 2, 0, 1, 1)
        self.label_kepco_start = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_kepco_start.setObjectName("label_kepco_start")
        self.gridLayout_8.addWidget(self.label_kepco_start, 9, 3, 1, 1)
        self.doubleSpinBox_scanDevStart = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_scanDevStart.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_scanDevStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevStart.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevStart.setKeyboardTracking(False)
        self.doubleSpinBox_scanDevStart.setDecimals(8)
        self.doubleSpinBox_scanDevStart.setMinimum(-10.0)
        self.doubleSpinBox_scanDevStart.setMaximum(10.0)
        self.doubleSpinBox_scanDevStart.setSingleStep(0.01)
        self.doubleSpinBox_scanDevStart.setObjectName("doubleSpinBox_scanDevStart")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevStart, 9, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 4, 0, 1, 1)
        self.doubleSpinBox_scanDev_timeout_s = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_scanDev_timeout_s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDev_timeout_s.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDev_timeout_s.setDecimals(3)
        self.doubleSpinBox_scanDev_timeout_s.setMaximum(1e+24)
        self.doubleSpinBox_scanDev_timeout_s.setObjectName("doubleSpinBox_scanDev_timeout_s")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDev_timeout_s, 7, 1, 1, 1)
        self.label_dacStartV_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_dacStartV_set.setObjectName("label_dacStartV_set")
        self.gridLayout_8.addWidget(self.label_dacStartV_set, 9, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 7, 0, 1, 1)
        self.doubleSpinBox_scanDevStop = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_scanDevStop.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_scanDevStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_scanDevStop.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_scanDevStop.setKeyboardTracking(False)
        self.doubleSpinBox_scanDevStop.setDecimals(8)
        self.doubleSpinBox_scanDevStop.setMinimum(-10.0)
        self.doubleSpinBox_scanDevStop.setMaximum(10.0)
        self.doubleSpinBox_scanDevStop.setSingleStep(0.01)
        self.doubleSpinBox_scanDevStop.setObjectName("doubleSpinBox_scanDevStop")
        self.gridLayout_8.addWidget(self.doubleSpinBox_scanDevStop, 10, 1, 1, 1)
        self.label_dacStopV_set = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_dacStopV_set.setObjectName("label_dacStopV_set")
        self.gridLayout_8.addWidget(self.label_dacStopV_set, 10, 2, 1, 1)
        self.label_dacStopV = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_dacStopV.setObjectName("label_dacStopV")
        self.gridLayout_8.addWidget(self.label_dacStopV, 10, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 21, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 2, 0, 2, 4)
        self.tabwidget.addTab(self.seqComSet, "")
        self.advancedSeqSettings = QtWidgets.QWidget()
        self.advancedSeqSettings.setObjectName("advancedSeqSettings")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.advancedSeqSettings)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.doubleSpinBox_waitAfterReset_muS = QtWidgets.QDoubleSpinBox(self.advancedSeqSettings)
        self.doubleSpinBox_waitAfterReset_muS.setFrame(True)
        self.doubleSpinBox_waitAfterReset_muS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_waitAfterReset_muS.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_waitAfterReset_muS.setKeyboardTracking(False)
        self.doubleSpinBox_waitAfterReset_muS.setDecimals(3)
        self.doubleSpinBox_waitAfterReset_muS.setMaximum(4200000.0)
        self.doubleSpinBox_waitAfterReset_muS.setSingleStep(0.5)
        self.doubleSpinBox_waitAfterReset_muS.setObjectName("doubleSpinBox_waitAfterReset_muS")
        self.gridLayout_6.addWidget(self.doubleSpinBox_waitAfterReset_muS, 2, 1, 1, 1)
        self.label_waitForKepco_muS = QtWidgets.QLabel(self.advancedSeqSettings)
        self.label_waitForKepco_muS.setObjectName("label_waitForKepco_muS")
        self.gridLayout_6.addWidget(self.label_waitForKepco_muS, 1, 0, 1, 1)
        self.doubleSpinBox_waitForKepco_muS = QtWidgets.QDoubleSpinBox(self.advancedSeqSettings)
        self.doubleSpinBox_waitForKepco_muS.setFrame(True)
        self.doubleSpinBox_waitForKepco_muS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_waitForKepco_muS.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_waitForKepco_muS.setKeyboardTracking(False)
        self.doubleSpinBox_waitForKepco_muS.setDecimals(3)
        self.doubleSpinBox_waitForKepco_muS.setMaximum(4200000.0)
        self.doubleSpinBox_waitForKepco_muS.setSingleStep(0.5)
        self.doubleSpinBox_waitForKepco_muS.setObjectName("doubleSpinBox_waitForKepco_muS")
        self.gridLayout_6.addWidget(self.doubleSpinBox_waitForKepco_muS, 1, 1, 1, 1)
        self.label_waitAfterReset_muS = QtWidgets.QLabel(self.advancedSeqSettings)
        self.label_waitAfterReset_muS.setObjectName("label_waitAfterReset_muS")
        self.gridLayout_6.addWidget(self.label_waitAfterReset_muS, 2, 0, 1, 1)
        self.label_waitForKepco_muS_set = QtWidgets.QLabel(self.advancedSeqSettings)
        self.label_waitForKepco_muS_set.setObjectName("label_waitForKepco_muS_set")
        self.gridLayout_6.addWidget(self.label_waitForKepco_muS_set, 1, 2, 1, 1)
        self.label_waitAfterReset_muS_set = QtWidgets.QLabel(self.advancedSeqSettings)
        self.label_waitAfterReset_muS_set.setObjectName("label_waitAfterReset_muS_set")
        self.gridLayout_6.addWidget(self.label_waitAfterReset_muS_set, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.advancedSeqSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.advancedSeqSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.advancedSeqSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabwidget.addTab(self.advancedSeqSettings, "")
        self.horizontalLayout_base.addWidget(self.tabwidget)
        self.verticalLayout_base.addLayout(self.horizontalLayout_base)
        self.gridWidgetButtons = QtWidgets.QWidget(self.centralwidget)
        self.gridWidgetButtons.setMinimumSize(QtCore.QSize(366, 50))
        self.gridWidgetButtons.setObjectName("gridWidgetButtons")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridWidgetButtons)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_cancel = QtWidgets.QPushButton(self.gridWidgetButtons)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_4.addWidget(self.pushButton_cancel, 0, 2, 1, 1)
        self.pushButtonResetToDefault = QtWidgets.QPushButton(self.gridWidgetButtons)
        self.pushButtonResetToDefault.setObjectName("pushButtonResetToDefault")
        self.gridLayout_4.addWidget(self.pushButtonResetToDefault, 0, 0, 1, 1)
        self.pushButton_confirm = QtWidgets.QPushButton(self.gridWidgetButtons)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.gridLayout_4.addWidget(self.pushButton_confirm, 0, 1, 1, 1)
        self.verticalLayout_base.addWidget(self.gridWidgetButtons)
        self.gridLayout_2.addLayout(self.verticalLayout_base, 0, 0, 1, 1)
        MainWindowTrackPars.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindowTrackPars)
        self.statusBar.setObjectName("statusBar")
        MainWindowTrackPars.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindowTrackPars)
        self.tabWidget.setCurrentIndex(0)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowTrackPars)

    def retranslateUi(self, MainWindowTrackPars):
        _translate = QtCore.QCoreApplication.translate
        MainWindowTrackPars.setWindowTitle(_translate("MainWindowTrackPars", "track parameters"))
        self.label_descriptionTrigger.setText(_translate("MainWindowTrackPars", "Standard trigger. Triggers measurements per bunch(TRS) or step(CS)"))
        self.label_Trigger.setText(_translate("MainWindowTrackPars", "trigger:"))
        self.checkBox_UseAllTracks.setText(_translate("MainWindowTrackPars", "use for all tracks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_trigger), _translate("MainWindowTrackPars", "meas Trigger"))
        self.label_descriptionStepTrigger.setText(_translate("MainWindowTrackPars", "Advanced trigger. Used to trigger next step. Usefull for laser scanning!"))
        self.label_stepTrigger.setText(_translate("MainWindowTrackPars", "step trigger:"))
        self.checkBox_stepUseAllTracks.setText(_translate("MainWindowTrackPars", "use for all tracks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_step_trigger), _translate("MainWindowTrackPars", "step Trigger"))
        self.label_18.setText(_translate("MainWindowTrackPars", "Advanced trigger. Used to trigger next scan."))
        self.label_scanTrigger.setText(_translate("MainWindowTrackPars", "scan trigger:"))
        self.checkBox_scanUseAllTracks.setText(_translate("MainWindowTrackPars", "use for all tracks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scan_trigger), _translate("MainWindowTrackPars", "scan Trigger"))
        self.pushButton_config_pulse_pattern.setText(_translate("MainWindowTrackPars", "configure pulse pattern"))
        self.pushButton_conf_pre_post_tr_meas.setText(_translate("MainWindowTrackPars", "configure dmm/triton measurements"))
        self.pushButton_con_outbits.setText(_translate("MainWindowTrackPars", "configure outbits"))
        self.label_dacStepSizeV.setText(_translate("MainWindowTrackPars", "scan dev step size"))
        self.label_kepco_stop.setText(_translate("MainWindowTrackPars", "None"))
        self.label_dacStepSizeV_set.setText(_translate("MainWindowTrackPars", "None"))
        self.pushButton_scanDev_pre_sc_copy_from_start.setText(_translate("MainWindowTrackPars", "copy start"))
        self.checkBox_scanDev_setPreScan.setText(_translate("MainWindowTrackPars", "Set"))
        self.label_14.setText(_translate("MainWindowTrackPars", "scan dev pre scan value"))
        self.label_15.setText(_translate("MainWindowTrackPars", "scan dev post scan value"))
        self.label_16.setText(_translate("MainWindowTrackPars", "scan device unit"))
        self.pushButton_scanDev_post_ssc_copy_stop.setText(_translate("MainWindowTrackPars", "copy stop"))
        self.label_scanDev_unit.setText(_translate("MainWindowTrackPars", "not defined"))
        self.checkBox_scanDev_setPostScan.setText(_translate("MainWindowTrackPars", "Set"))
        self.label_7.setText(_translate("MainWindowTrackPars", "DAC * 50"))
        self.label_5.setText(_translate("MainWindowTrackPars", "Set Value"))
        self.label_4.setText(_translate("MainWindowTrackPars", "User Input"))
        self.label_3.setText(_translate("MainWindowTrackPars", "Parameter"))
        self.label_kepco_step.setText(_translate("MainWindowTrackPars", "None"))
        self.label_nOfScans_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_nOfSteps.setText(_translate("MainWindowTrackPars", "number of steps"))
        self.label_nOfSteps_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_nOfScans.setText(_translate("MainWindowTrackPars", "number of Scans"))
        self.comboBox_postAccOffsetVoltControl.setItemText(0, _translate("MainWindowTrackPars", "Kepco"))
        self.comboBox_postAccOffsetVoltControl.setItemText(1, _translate("MainWindowTrackPars", "Heinzinger1"))
        self.comboBox_postAccOffsetVoltControl.setItemText(2, _translate("MainWindowTrackPars", "Heinzinger2"))
        self.comboBox_postAccOffsetVoltControl.setItemText(3, _translate("MainWindowTrackPars", "Heinzinger3"))
        self.label_invertScan_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_postAccOffsetVolt.setText(_translate("MainWindowTrackPars", "post Acceleration \n"
"power supply voltage [V]"))
        self.label_invertScan.setText(_translate("MainWindowTrackPars", "invert scan direction"))
        self.label_11.setText(_translate("MainWindowTrackPars", "readback\n"
"Voltage:"))
        self.label_postAccOffsetVoltControl.setText(_translate("MainWindowTrackPars", "post Acceleration \n"
"power supply"))
        self.label_postAccOffsetVoltControl_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_colDirTrue.setText(_translate("MainWindowTrackPars", "measured collinear?"))
        self.label_activePmtList_set.setText(_translate("MainWindowTrackPars", "None"))
        self.pushButton_postAccOffsetVolt.setText(_translate("MainWindowTrackPars", "set volt"))
        self.label_activePmtList.setText(_translate("MainWindowTrackPars", "active PMT List"))
        self.label_postAccOffsetVolt_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_8.setText(_translate("MainWindowTrackPars", "scan device type"))
        self.label_colDirTrue_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_dacStartV.setText(_translate("MainWindowTrackPars", "scan dev start"))
        self.label.setText(_translate("MainWindowTrackPars", "scan device class"))
        self.label_kepco_start.setText(_translate("MainWindowTrackPars", "None"))
        self.label_10.setText(_translate("MainWindowTrackPars", "scan device name"))
        self.label_dacStartV_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_12.setText(_translate("MainWindowTrackPars", "scan device timeout [s]"))
        self.label_dacStopV_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_dacStopV.setText(_translate("MainWindowTrackPars", "scan dev stop"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.seqComSet), _translate("MainWindowTrackPars", "common Sequencer Settings"))
        self.label_waitForKepco_muS.setText(_translate("MainWindowTrackPars", "wait after each voltage set [µs]"))
        self.label_waitAfterReset_muS.setText(_translate("MainWindowTrackPars", "wait after voltage reset [µs]"))
        self.label_waitForKepco_muS_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_waitAfterReset_muS_set.setText(_translate("MainWindowTrackPars", "None"))
        self.label_6.setText(_translate("MainWindowTrackPars", "user input"))
        self.label_13.setText(_translate("MainWindowTrackPars", "set value"))
        self.label_2.setText(_translate("MainWindowTrackPars", "parameter"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.advancedSeqSettings), _translate("MainWindowTrackPars", "advanced Settings"))
        self.pushButton_cancel.setText(_translate("MainWindowTrackPars", "cancel"))
        self.pushButtonResetToDefault.setText(_translate("MainWindowTrackPars", "reset to default"))
        self.pushButton_confirm.setText(_translate("MainWindowTrackPars", "confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowTrackPars = QtWidgets.QMainWindow()
    ui = Ui_MainWindowTrackPars()
    ui.setupUi(MainWindowTrackPars)
    MainWindowTrackPars.show()
    sys.exit(app.exec_())

