# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_TrackPar.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowTrackPars(object):
    def setupUi(self, MainWindowTrackPars):
        MainWindowTrackPars.setObjectName("MainWindowTrackPars")
        MainWindowTrackPars.resize(389, 472)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("track_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowTrackPars.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindowTrackPars)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_dwellTime_ms = QtWidgets.QLabel(self.widget)
        self.label_dwellTime_ms.setObjectName("label_dwellTime_ms")
        self.gridLayout.addWidget(self.label_dwellTime_ms, 1, 0, 1, 1)
        self.doubleSpinBox_dwellTime_ms = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_dwellTime_ms.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_dwellTime_ms.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_dwellTime_ms.setKeyboardTracking(False)
        self.doubleSpinBox_dwellTime_ms.setDecimals(5)
        self.doubleSpinBox_dwellTime_ms.setMaximum(1000.0)
        self.doubleSpinBox_dwellTime_ms.setObjectName("doubleSpinBox_dwellTime_ms")
        self.gridLayout.addWidget(self.doubleSpinBox_dwellTime_ms, 1, 1, 1, 1)
        self.label_dwellTime_ms_2 = QtWidgets.QLabel(self.widget)
        self.label_dwellTime_ms_2.setObjectName("label_dwellTime_ms_2")
        self.gridLayout.addWidget(self.label_dwellTime_ms_2, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_activePmtList = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_activePmtList.sizePolicy().hasHeightForWidth())
        self.lineEdit_activePmtList.setSizePolicy(sizePolicy)
        self.lineEdit_activePmtList.setText("")
        self.lineEdit_activePmtList.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_activePmtList.setObjectName("lineEdit_activePmtList")
        self.gridLayout_4.addWidget(self.lineEdit_activePmtList, 9, 1, 1, 1)
        self.label_nOfScans = QtWidgets.QLabel(self.widget_3)
        self.label_nOfScans.setObjectName("label_nOfScans")
        self.gridLayout_4.addWidget(self.label_nOfScans, 5, 0, 1, 1)
        self.doubleSpinBox_postAccOffsetVolt = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox_postAccOffsetVolt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_postAccOffsetVolt.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_postAccOffsetVolt.setKeyboardTracking(False)
        self.doubleSpinBox_postAccOffsetVolt.setObjectName("doubleSpinBox_postAccOffsetVolt")
        self.gridLayout_4.addWidget(self.doubleSpinBox_postAccOffsetVolt, 8, 1, 1, 1)
        self.label_invertScan = QtWidgets.QLabel(self.widget_3)
        self.label_invertScan.setObjectName("label_invertScan")
        self.gridLayout_4.addWidget(self.label_invertScan, 6, 0, 1, 1)
        self.label_dacStartV_set = QtWidgets.QLabel(self.widget_3)
        self.label_dacStartV_set.setObjectName("label_dacStartV_set")
        self.gridLayout_4.addWidget(self.label_dacStartV_set, 1, 2, 1, 1)
        self.doubleSpinBox_dacStartV = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox_dacStartV.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_dacStartV.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_dacStartV.setKeyboardTracking(False)
        self.doubleSpinBox_dacStartV.setDecimals(8)
        self.doubleSpinBox_dacStartV.setMaximum(10.0)
        self.doubleSpinBox_dacStartV.setSingleStep(1e-06)
        self.doubleSpinBox_dacStartV.setObjectName("doubleSpinBox_dacStartV")
        self.gridLayout_4.addWidget(self.doubleSpinBox_dacStartV, 1, 1, 1, 1)
        self.checkBox_invertScan = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox_invertScan.setText("")
        self.checkBox_invertScan.setObjectName("checkBox_invertScan")
        self.gridLayout_4.addWidget(self.checkBox_invertScan, 6, 1, 1, 1)
        self.label_activePmtList = QtWidgets.QLabel(self.widget_3)
        self.label_activePmtList.setObjectName("label_activePmtList")
        self.gridLayout_4.addWidget(self.label_activePmtList, 9, 0, 1, 1)
        self.label_postAccOffsetVolt = QtWidgets.QLabel(self.widget_3)
        self.label_postAccOffsetVolt.setObjectName("label_postAccOffsetVolt")
        self.gridLayout_4.addWidget(self.label_postAccOffsetVolt, 8, 0, 1, 1)
        self.spinBox_postAccOffsetVoltControl = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_postAccOffsetVoltControl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_postAccOffsetVoltControl.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_postAccOffsetVoltControl.setKeyboardTracking(False)
        self.spinBox_postAccOffsetVoltControl.setObjectName("spinBox_postAccOffsetVoltControl")
        self.gridLayout_4.addWidget(self.spinBox_postAccOffsetVoltControl, 7, 1, 1, 1)
        self.label_postAccOffsetVolt_set = QtWidgets.QLabel(self.widget_3)
        self.label_postAccOffsetVolt_set.setObjectName("label_postAccOffsetVolt_set")
        self.gridLayout_4.addWidget(self.label_postAccOffsetVolt_set, 8, 2, 1, 1)
        self.label_postAccOffsetVoltControl_set = QtWidgets.QLabel(self.widget_3)
        self.label_postAccOffsetVoltControl_set.setObjectName("label_postAccOffsetVoltControl_set")
        self.gridLayout_4.addWidget(self.label_postAccOffsetVoltControl_set, 7, 2, 1, 1)
        self.spinBox_nOfScans = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_nOfScans.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_nOfScans.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nOfScans.setKeyboardTracking(False)
        self.spinBox_nOfScans.setObjectName("spinBox_nOfScans")
        self.gridLayout_4.addWidget(self.spinBox_nOfScans, 5, 1, 1, 1)
        self.label_nOfScans_set = QtWidgets.QLabel(self.widget_3)
        self.label_nOfScans_set.setObjectName("label_nOfScans_set")
        self.gridLayout_4.addWidget(self.label_nOfScans_set, 5, 2, 1, 1)
        self.checkBox_colDirTrue = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox_colDirTrue.setText("")
        self.checkBox_colDirTrue.setObjectName("checkBox_colDirTrue")
        self.gridLayout_4.addWidget(self.checkBox_colDirTrue, 10, 1, 1, 1)
        self.label_colDirTrue = QtWidgets.QLabel(self.widget_3)
        self.label_colDirTrue.setObjectName("label_colDirTrue")
        self.gridLayout_4.addWidget(self.label_colDirTrue, 10, 0, 1, 1)
        self.label_colDirTrue_set = QtWidgets.QLabel(self.widget_3)
        self.label_colDirTrue_set.setObjectName("label_colDirTrue_set")
        self.gridLayout_4.addWidget(self.label_colDirTrue_set, 10, 2, 1, 1)
        self.pushButton_advancedSettings = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_advancedSettings.setObjectName("pushButton_advancedSettings")
        self.gridLayout_4.addWidget(self.pushButton_advancedSettings, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_dacStartV = QtWidgets.QLabel(self.widget_3)
        self.label_dacStartV.setObjectName("label_dacStartV")
        self.gridLayout_4.addWidget(self.label_dacStartV, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_postAccOffsetVoltControl = QtWidgets.QLabel(self.widget_3)
        self.label_postAccOffsetVoltControl.setObjectName("label_postAccOffsetVoltControl")
        self.gridLayout_4.addWidget(self.label_postAccOffsetVoltControl, 7, 0, 1, 1)
        self.label_dacStopV_set = QtWidgets.QLabel(self.widget_3)
        self.label_dacStopV_set.setObjectName("label_dacStopV_set")
        self.gridLayout_4.addWidget(self.label_dacStopV_set, 2, 2, 1, 1)
        self.label_dacStepSizeV = QtWidgets.QLabel(self.widget_3)
        self.label_dacStepSizeV.setObjectName("label_dacStepSizeV")
        self.gridLayout_4.addWidget(self.label_dacStepSizeV, 3, 0, 1, 1)
        self.label_dacStopV = QtWidgets.QLabel(self.widget_3)
        self.label_dacStopV.setObjectName("label_dacStopV")
        self.gridLayout_4.addWidget(self.label_dacStopV, 2, 0, 1, 1)
        self.label_nOfSteps_set = QtWidgets.QLabel(self.widget_3)
        self.label_nOfSteps_set.setObjectName("label_nOfSteps_set")
        self.gridLayout_4.addWidget(self.label_nOfSteps_set, 4, 2, 1, 1)
        self.spinBox_nOfSteps = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_nOfSteps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_nOfSteps.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nOfSteps.setKeyboardTracking(False)
        self.spinBox_nOfSteps.setObjectName("spinBox_nOfSteps")
        self.gridLayout_4.addWidget(self.spinBox_nOfSteps, 4, 1, 1, 1)
        self.label_dacStepSizeV_set = QtWidgets.QLabel(self.widget_3)
        self.label_dacStepSizeV_set.setObjectName("label_dacStepSizeV_set")
        self.gridLayout_4.addWidget(self.label_dacStepSizeV_set, 3, 2, 1, 1)
        self.label_nOfSteps = QtWidgets.QLabel(self.widget_3)
        self.label_nOfSteps.setObjectName("label_nOfSteps")
        self.gridLayout_4.addWidget(self.label_nOfSteps, 4, 0, 1, 1)
        self.label_activePmtList_set = QtWidgets.QLabel(self.widget_3)
        self.label_activePmtList_set.setObjectName("label_activePmtList_set")
        self.gridLayout_4.addWidget(self.label_activePmtList_set, 9, 2, 1, 1)
        self.doubleSpinBox_dacStopV = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox_dacStopV.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_dacStopV.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_dacStopV.setKeyboardTracking(False)
        self.doubleSpinBox_dacStopV.setDecimals(8)
        self.doubleSpinBox_dacStopV.setMaximum(10.0)
        self.doubleSpinBox_dacStopV.setSingleStep(1e-06)
        self.doubleSpinBox_dacStopV.setObjectName("doubleSpinBox_dacStopV")
        self.gridLayout_4.addWidget(self.doubleSpinBox_dacStopV, 2, 1, 1, 1)
        self.label_invertScan_set = QtWidgets.QLabel(self.widget_3)
        self.label_invertScan_set.setObjectName("label_invertScan_set")
        self.gridLayout_4.addWidget(self.label_invertScan_set, 6, 2, 1, 1)
        self.doubleSpinBox_dacStepSizeV = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox_dacStepSizeV.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_dacStepSizeV.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_dacStepSizeV.setKeyboardTracking(False)
        self.doubleSpinBox_dacStepSizeV.setDecimals(8)
        self.doubleSpinBox_dacStepSizeV.setMaximum(10.0)
        self.doubleSpinBox_dacStepSizeV.setSingleStep(1e-06)
        self.doubleSpinBox_dacStepSizeV.setObjectName("doubleSpinBox_dacStepSizeV")
        self.gridLayout_4.addWidget(self.doubleSpinBox_dacStepSizeV, 3, 1, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_4.addWidget(self.pushButton_cancel, 11, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton_confirm = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.gridLayout_4.addWidget(self.pushButton_confirm, 11, 2, 1, 1)
        self.label_kepco_start = QtWidgets.QLabel(self.widget_3)
        self.label_kepco_start.setObjectName("label_kepco_start")
        self.gridLayout_4.addWidget(self.label_kepco_start, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_kepco_stop = QtWidgets.QLabel(self.widget_3)
        self.label_kepco_stop.setObjectName("label_kepco_stop")
        self.gridLayout_4.addWidget(self.label_kepco_stop, 2, 3, 1, 1)
        self.label_kepco_step = QtWidgets.QLabel(self.widget_3)
        self.label_kepco_step.setObjectName("label_kepco_step")
        self.gridLayout_4.addWidget(self.label_kepco_step, 3, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.widget_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindowTrackPars.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowTrackPars)
        self.statusbar.setObjectName("statusbar")
        MainWindowTrackPars.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowTrackPars)
        QtCore.QMetaObject.connectSlotsByName(MainWindowTrackPars)

    def retranslateUi(self, MainWindowTrackPars):
        _translate = QtCore.QCoreApplication.translate
        MainWindowTrackPars.setWindowTitle(_translate("MainWindowTrackPars", "track parameters"))
        self.label.setText(_translate("MainWindowTrackPars", "Continous Sequencer Settings"))
        self.label_dwellTime_ms.setText(_translate("MainWindowTrackPars", "dwell time [ms]"))
        self.label_dwellTime_ms_2.setText(_translate("MainWindowTrackPars", "0"))
        self.label_8.setText(_translate("MainWindowTrackPars", "Parameter"))
        self.label_9.setText(_translate("MainWindowTrackPars", "User Input"))
        self.label_10.setText(_translate("MainWindowTrackPars", "Set Value"))
        self.label_2.setText(_translate("MainWindowTrackPars", "Common Sequencer Settings"))
        self.label_nOfScans.setText(_translate("MainWindowTrackPars", "number of Scans"))
        self.label_invertScan.setText(_translate("MainWindowTrackPars", "invert scan direction"))
        self.label_dacStartV_set.setText(_translate("MainWindowTrackPars", "0"))
        self.label_activePmtList.setText(_translate("MainWindowTrackPars", "active PMT List"))
        self.label_postAccOffsetVolt.setText(_translate("MainWindowTrackPars", "post Acceleration \n"
"power supply voltage [V]"))
        self.label_postAccOffsetVolt_set.setText(_translate("MainWindowTrackPars", "0"))
        self.label_postAccOffsetVoltControl_set.setText(_translate("MainWindowTrackPars", "0"))
        self.label_nOfScans_set.setText(_translate("MainWindowTrackPars", "0"))
        self.label_colDirTrue.setText(_translate("MainWindowTrackPars", "measured collinear?"))
        self.label_colDirTrue_set.setText(_translate("MainWindowTrackPars", "anti collinear"))
        self.pushButton_advancedSettings.setText(_translate("MainWindowTrackPars", "advanced settings"))
        self.label_5.setText(_translate("MainWindowTrackPars", "Set Value"))
        self.label_dacStartV.setText(_translate("MainWindowTrackPars", "DAC start  [V]"))
        self.label_4.setText(_translate("MainWindowTrackPars", "User Input"))
        self.label_postAccOffsetVoltControl.setText(_translate("MainWindowTrackPars", "post Acceleration \n"
"power supply number"))
        self.label_dacStopV_set.setText(_translate("MainWindowTrackPars", "0"))
        self.label_dacStepSizeV.setText(_translate("MainWindowTrackPars", "DAC step size [V]"))
        self.label_dacStopV.setText(_translate("MainWindowTrackPars", "DAC stop [V]"))
        self.label_nOfSteps_set.setText(_translate("MainWindowTrackPars", "0"))
        self.label_dacStepSizeV_set.setText(_translate("MainWindowTrackPars", "0"))
        self.label_nOfSteps.setText(_translate("MainWindowTrackPars", "number of steps"))
        self.label_activePmtList_set.setText(_translate("MainWindowTrackPars", "[]"))
        self.label_invertScan_set.setText(_translate("MainWindowTrackPars", "False"))
        self.pushButton_cancel.setText(_translate("MainWindowTrackPars", "cancel"))
        self.label_3.setText(_translate("MainWindowTrackPars", "Parameter"))
        self.pushButton_confirm.setText(_translate("MainWindowTrackPars", "confirm"))
        self.label_kepco_start.setText(_translate("MainWindowTrackPars", "0"))
        self.label_7.setText(_translate("MainWindowTrackPars", "DAC * 50"))
        self.label_kepco_stop.setText(_translate("MainWindowTrackPars", "0"))
        self.label_kepco_step.setText(_translate("MainWindowTrackPars", "0"))

