# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AddFiles.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_AddFiles(object):
    def setupUi(self, AddFiles):
        AddFiles.setObjectName("AddFiles")
        AddFiles.resize(603, 423)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AddFiles)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.isoFilter = QtWidgets.QComboBox(AddFiles)
        self.isoFilter.setObjectName("isoFilter")
        self.verticalLayout_3.addWidget(self.isoFilter)
        self.widget = QtWidgets.QWidget(AddFiles)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.fileList = QtWidgets.QListWidget(self.widget)
        self.fileList.setObjectName("fileList")
        self.gridLayout.addWidget(self.fileList, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_host_file_set = QtWidgets.QLabel(self.widget_3)
        self.label_host_file_set.setObjectName("label_host_file_set")
        self.verticalLayout.addWidget(self.label_host_file_set)
        self.pushButton_clear = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout.addWidget(self.pushButton_clear)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.listWidget_added_files = QtWidgets.QListWidget(self.widget_3)
        self.listWidget_added_files.setObjectName("listWidget_added_files")
        self.verticalLayout.addWidget(self.listWidget_added_files)
        self.pushButton_save = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.pushButton_save)
        self.gridLayout.addWidget(self.widget_3, 0, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_choose_host_file = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_choose_host_file.setObjectName("pushButton_choose_host_file")
        self.verticalLayout_2.addWidget(self.pushButton_choose_host_file)
        self.pushButton_add_file = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_add_file.setObjectName("pushButton_add_file")
        self.verticalLayout_2.addWidget(self.pushButton_add_file)
        self.pushButton_substract_file = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_substract_file.setObjectName("pushButton_substract_file")
        self.verticalLayout_2.addWidget(self.pushButton_substract_file)
        self.pushButton_remove_file = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_remove_file.setObjectName("pushButton_remove_file")
        self.verticalLayout_2.addWidget(self.pushButton_remove_file)
        self.gridLayout.addWidget(self.widget_2, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.widget)
        self.label_2 = QtWidgets.QLabel(AddFiles)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_last_saved = QtWidgets.QLabel(AddFiles)
        self.label_last_saved.setObjectName("label_last_saved")
        self.verticalLayout_3.addWidget(self.label_last_saved)

        self.retranslateUi(AddFiles)
        QtCore.QMetaObject.connectSlotsByName(AddFiles)

    def retranslateUi(self, AddFiles):
        _translate = QtCore.QCoreApplication.translate
        AddFiles.setWindowTitle(_translate("AddFiles", "Form"))
        self.label.setText(_translate("AddFiles", "host file:"))
        self.label_host_file_set.setText(_translate("AddFiles", "None"))
        self.pushButton_clear.setText(_translate("AddFiles", "clear"))
        self.label_3.setText(_translate("AddFiles", "files to add/subtract:"))
        self.pushButton_save.setText(_translate("AddFiles", "create and save"))
        self.pushButton_choose_host_file.setText(_translate("AddFiles", "choose host File"))
        self.pushButton_add_file.setText(_translate("AddFiles", "add File"))
        self.pushButton_substract_file.setText(_translate("AddFiles", "substract File"))
        self.pushButton_remove_file.setText(_translate("AddFiles", "remove File"))
        self.label_2.setText(_translate("AddFiles", "last saved:"))
        self.label_last_saved.setText(_translate("AddFiles", "None"))

