# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ColAcol.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ColAcol(object):
    def setupUi(self, ColAcol):
        ColAcol.setObjectName("ColAcol")
        ColAcol.setWindowModality(QtCore.Qt.NonModal)
        ColAcol.resize(869, 610)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(ColAcol)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.coColIso = QtWidgets.QComboBox(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coColIso.sizePolicy().hasHeightForWidth())
        self.coColIso.setSizePolicy(sizePolicy)
        self.coColIso.setObjectName("coColIso")
        self.horizontalLayout_8.addWidget(self.coColIso)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.coColRun = QtWidgets.QComboBox(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coColRun.sizePolicy().hasHeightForWidth())
        self.coColRun.setSizePolicy(sizePolicy)
        self.coColRun.setObjectName("coColRun")
        self.horizontalLayout_6.addWidget(self.coColRun)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.oCol = QtWidgets.QLabel(ColAcol)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oCol.setFont(font)
        self.oCol.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.oCol.setAlignment(QtCore.Qt.AlignCenter)
        self.oCol.setObjectName("oCol")
        self.verticalLayout_2.addWidget(self.oCol)
        self.lCol = QtWidgets.QListWidget(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lCol.sizePolicy().hasHeightForWidth())
        self.lCol.setSizePolicy(sizePolicy)
        self.lCol.setMinimumSize(QtCore.QSize(185, 300))
        self.lCol.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lCol.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.lCol.setObjectName("lCol")
        self.verticalLayout_2.addWidget(self.lCol)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.oArrow = QtWidgets.QLabel(ColAcol)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.oArrow.setFont(font)
        self.oArrow.setObjectName("oArrow")
        self.horizontalLayout.addWidget(self.oArrow)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.coAcolIso = QtWidgets.QComboBox(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coAcolIso.sizePolicy().hasHeightForWidth())
        self.coAcolIso.setSizePolicy(sizePolicy)
        self.coAcolIso.setObjectName("coAcolIso")
        self.horizontalLayout_9.addWidget(self.coAcolIso)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.coAcolRun = QtWidgets.QComboBox(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coAcolRun.sizePolicy().hasHeightForWidth())
        self.coAcolRun.setSizePolicy(sizePolicy)
        self.coAcolRun.setObjectName("coAcolRun")
        self.horizontalLayout_5.addWidget(self.coAcolRun)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.oAcol = QtWidgets.QLabel(ColAcol)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oAcol.setFont(font)
        self.oAcol.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.oAcol.setAlignment(QtCore.Qt.AlignCenter)
        self.oAcol.setObjectName("oAcol")
        self.verticalLayout_3.addWidget(self.oAcol)
        self.lAcol = QtWidgets.QListWidget(ColAcol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lAcol.sizePolicy().hasHeightForWidth())
        self.lAcol.setSizePolicy(sizePolicy)
        self.lAcol.setMinimumSize(QtCore.QSize(185, 300))
        self.lAcol.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lAcol.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.lAcol.setObjectName("lAcol")
        self.verticalLayout_3.addWidget(self.lAcol)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bRemove = QtWidgets.QPushButton(ColAcol)
        self.bRemove.setMinimumSize(QtCore.QSize(185, 25))
        self.bRemove.setMaximumSize(QtCore.QSize(185, 25))
        self.bRemove.setObjectName("bRemove")
        self.horizontalLayout_2.addWidget(self.bRemove)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.oFile = QtWidgets.QLabel(ColAcol)
        self.oFile.setMinimumSize(QtCore.QSize(70, 25))
        self.oFile.setMaximumSize(QtCore.QSize(16777215, 25))
        self.oFile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oFile.setObjectName("oFile")
        self.horizontalLayout_2.addWidget(self.oFile)
        self.iFile = QtWidgets.QLineEdit(ColAcol)
        self.iFile.setMinimumSize(QtCore.QSize(350, 25))
        self.iFile.setMaximumSize(QtCore.QSize(350, 25))
        self.iFile.setObjectName("iFile")
        self.horizontalLayout_2.addWidget(self.iFile)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.oPath = QtWidgets.QLabel(ColAcol)
        self.oPath.setMinimumSize(QtCore.QSize(70, 25))
        self.oPath.setMaximumSize(QtCore.QSize(20000, 25))
        self.oPath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oPath.setObjectName("oPath")
        self.horizontalLayout_3.addWidget(self.oPath)
        self.iPath = QtWidgets.QLineEdit(ColAcol)
        self.iPath.setMinimumSize(QtCore.QSize(350, 25))
        self.iPath.setMaximumSize(QtCore.QSize(350, 25))
        self.iPath.setObjectName("iPath")
        self.horizontalLayout_3.addWidget(self.iPath)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.bStart = QtWidgets.QPushButton(ColAcol)
        self.bStart.setMinimumSize(QtCore.QSize(350, 25))
        self.bStart.setMaximumSize(QtCore.QSize(350, 25))
        self.bStart.setObjectName("bStart")
        self.horizontalLayout_4.addWidget(self.bStart)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)

        self.retranslateUi(ColAcol)
        QtCore.QMetaObject.connectSlotsByName(ColAcol)

    def retranslateUi(self, ColAcol):
        _translate = QtCore.QCoreApplication.translate
        ColAcol.setWindowTitle(_translate("ColAcol", "Form"))
        self.label_4.setText(_translate("ColAcol", "Col Isotope:   "))
        self.label_2.setText(_translate("ColAcol", "Col Run:         "))
        self.oCol.setText(_translate("ColAcol", "Collinear spectra"))
        self.oArrow.setText(_translate("ColAcol", "↔"))
        self.label_5.setText(_translate("ColAcol", "Acol Isotope:   "))
        self.label.setText(_translate("ColAcol", "Acol Run:         "))
        self.oAcol.setText(_translate("ColAcol", "Anti-collinear spectra"))
        self.bRemove.setText(_translate("ColAcol", "Remove marked spectra"))
        self.oFile.setText(_translate("ColAcol", "File Name"))
        self.oPath.setText(_translate("ColAcol", "Output Path"))
        self.bStart.setText(_translate("ColAcol", "Start!"))

