[metadata]
name = proteus
version = 1.0.7
description = Framework for data exchange and distributed experiment control.
long_description = file: README.md
author = Daniel Kabuß
author_email = daniel.kabuss@stud.tu-darmstadt.de
url = https://github.com/lasersphere/proteus
license = European Union Public Licence v. 1.2
license_files = 
	LICENSE
classifiers = 
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)",
	"Operating System :: OS Independent",
	"Intended Audience :: Science/Research",
	"Topic :: Scientific/Engineering :: Physics",
	"Topic :: Software Development :: Libraries :: Application Frameworks",

[options]
package_dir = 
	=src
packages = find:
install_requires = 
	PyQt5 >= 5.13
	PyQt5-tools >= 5.13
	pyzmq >= 22.0

[options.packages.find]
where = src
exclude = 
	proteus.deprecated*

[egg_info]
tag_build = 
tag_date = 0

