# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Users\Patrick\Documents\Python Projects\Tilda\TildaHost\source\Interface\PreScanConfigUi\Ui_PreScanMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreScanMainWin(object):
    def setupUi(self, PreScanMainWin):
        PreScanMainWin.setObjectName("PreScanMainWin")
        PreScanMainWin.resize(398, 575)
        PreScanMainWin.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(PreScanMainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.volt_tab = QtWidgets.QWidget()
        self.volt_tab.setObjectName("volt_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.volt_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.voltage_mainwidget = QtWidgets.QWidget(self.volt_tab)
        self.voltage_mainwidget.setObjectName("voltage_mainwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.voltage_mainwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_voltage_measure = QtWidgets.QCheckBox(self.voltage_mainwidget)
        self.checkBox_voltage_measure.setObjectName("checkBox_voltage_measure")
        self.verticalLayout_3.addWidget(self.checkBox_voltage_measure)
        self.tabWidget = QtWidgets.QTabWidget(self.voltage_mainwidget)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.tabWidget.addTab(self.tab_0, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.voltage_mainwidget)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_measVoltPulseLength_mu_s = QtWidgets.QLabel(self.volt_tab)
        self.label_measVoltPulseLength_mu_s.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_measVoltPulseLength_mu_s.setObjectName("label_measVoltPulseLength_mu_s")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_measVoltPulseLength_mu_s)
        self.label_measVoltTimeout_mu_s = QtWidgets.QLabel(self.volt_tab)
        self.label_measVoltTimeout_mu_s.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_measVoltTimeout_mu_s.setObjectName("label_measVoltTimeout_mu_s")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_measVoltTimeout_mu_s)
        self.doubleSpinBox_measVoltTimeout_mu_s_set = QtWidgets.QDoubleSpinBox(self.volt_tab)
        self.doubleSpinBox_measVoltTimeout_mu_s_set.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_measVoltTimeout_mu_s_set.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_measVoltTimeout_mu_s_set.setKeyboardTracking(False)
        self.doubleSpinBox_measVoltTimeout_mu_s_set.setDecimals(3)
        self.doubleSpinBox_measVoltTimeout_mu_s_set.setMaximum(42949.0)
        self.doubleSpinBox_measVoltTimeout_mu_s_set.setObjectName("doubleSpinBox_measVoltTimeout_mu_s_set")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_measVoltTimeout_mu_s_set)
        self.doubleSpinBox_measVoltPulseLength_mu_s = QtWidgets.QDoubleSpinBox(self.volt_tab)
        self.doubleSpinBox_measVoltPulseLength_mu_s.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_measVoltPulseLength_mu_s.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_measVoltPulseLength_mu_s.setKeyboardTracking(False)
        self.doubleSpinBox_measVoltPulseLength_mu_s.setDecimals(3)
        self.doubleSpinBox_measVoltPulseLength_mu_s.setMaximum(107374182.0)
        self.doubleSpinBox_measVoltPulseLength_mu_s.setObjectName("doubleSpinBox_measVoltPulseLength_mu_s")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_measVoltPulseLength_mu_s)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.mainTabWidget.addTab(self.volt_tab, "")
        self.triton_tab = QtWidgets.QWidget()
        self.triton_tab.setObjectName("triton_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.triton_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_triton_measure = QtWidgets.QCheckBox(self.triton_tab)
        self.checkBox_triton_measure.setObjectName("checkBox_triton_measure")
        self.verticalLayout_6.addWidget(self.checkBox_triton_measure)
        self.splitter = QtWidgets.QSplitter(self.triton_tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.listWidget_devices = QtWidgets.QListWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_devices.sizePolicy().hasHeightForWidth())
        self.listWidget_devices.setSizePolicy(sizePolicy)
        self.listWidget_devices.setObjectName("listWidget_devices")
        self.verticalLayout_5.addWidget(self.listWidget_devices)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_channels = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_channels.setObjectName("label_channels")
        self.verticalLayout_4.addWidget(self.label_channels)
        self.tableWidget_channels = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget_channels.setObjectName("tableWidget_channels")
        self.tableWidget_channels.setColumnCount(0)
        self.tableWidget_channels.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_channels)
        self.verticalLayout_6.addWidget(self.splitter)
        self.mainTabWidget.addTab(self.triton_tab, "")
        self.sql_tab = QtWidgets.QWidget()
        self.sql_tab.setObjectName("sql_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sql_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.check_sql_measure = QtWidgets.QCheckBox(self.sql_tab)
        self.check_sql_measure.setObjectName("check_sql_measure")
        self.verticalLayout_7.addWidget(self.check_sql_measure)
        self.scroll_measure = QtWidgets.QScrollArea(self.sql_tab)
        self.scroll_measure.setWidgetResizable(True)
        self.scroll_measure.setObjectName("scroll_measure")
        self.scroll_widget_measure = QtWidgets.QWidget()
        self.scroll_widget_measure.setGeometry(QtCore.QRect(0, 0, 354, 170))
        self.scroll_widget_measure.setObjectName("scroll_widget_measure")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scroll_widget_measure)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.grid_db_measure = QtWidgets.QGridLayout()
        self.grid_db_measure.setObjectName("grid_db_measure")
        self.label_db_measure = QtWidgets.QLabel(self.scroll_widget_measure)
        self.label_db_measure.setObjectName("label_db_measure")
        self.grid_db_measure.addWidget(self.label_db_measure, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.grid_db_measure.addItem(spacerItem, 1, 2, 1, 1)
        self.combo_db_measure = QtWidgets.QComboBox(self.scroll_widget_measure)
        self.combo_db_measure.setObjectName("combo_db_measure")
        self.grid_db_measure.addWidget(self.combo_db_measure, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_db_measure.addItem(spacerItem1, 1, 1, 1, 1)
        self.grid_db_measure.setColumnStretch(0, 1)
        self.grid_db_measure.setColumnStretch(1, 1)
        self.verticalLayout_8.addLayout(self.grid_db_measure)
        self.hor_add = QtWidgets.QHBoxLayout()
        self.hor_add.setObjectName("hor_add")
        self.b_add_measure = QtWidgets.QPushButton(self.scroll_widget_measure)
        self.b_add_measure.setMaximumSize(QtCore.QSize(50, 16777215))
        self.b_add_measure.setObjectName("b_add_measure")
        self.hor_add.addWidget(self.b_add_measure)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_add.addItem(spacerItem2)
        self.hor_add.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.hor_add)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.verticalLayout_8.setStretch(2, 1)
        self.scroll_measure.setWidget(self.scroll_widget_measure)
        self.verticalLayout_7.addWidget(self.scroll_measure)
        self.line = QtWidgets.QFrame(self.sql_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.check_sql_send = QtWidgets.QCheckBox(self.sql_tab)
        self.check_sql_send.setObjectName("check_sql_send")
        self.verticalLayout_7.addWidget(self.check_sql_send)
        self.scroll_send = QtWidgets.QScrollArea(self.sql_tab)
        self.scroll_send.setWidgetResizable(True)
        self.scroll_send.setObjectName("scroll_send")
        self.scroll_widget_send = QtWidgets.QWidget()
        self.scroll_widget_send.setGeometry(QtCore.QRect(0, 0, 354, 169))
        self.scroll_widget_send.setObjectName("scroll_widget_send")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scroll_widget_send)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.grid_db_send = QtWidgets.QGridLayout()
        self.grid_db_send.setObjectName("grid_db_send")
        self.label_db_send = QtWidgets.QLabel(self.scroll_widget_send)
        self.label_db_send.setObjectName("label_db_send")
        self.grid_db_send.addWidget(self.label_db_send, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.grid_db_send.addItem(spacerItem4, 1, 2, 1, 1)
        self.combo_db_send = QtWidgets.QComboBox(self.scroll_widget_send)
        self.combo_db_send.setObjectName("combo_db_send")
        self.grid_db_send.addWidget(self.combo_db_send, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_db_send.addItem(spacerItem5, 1, 1, 1, 1)
        self.grid_db_send.setColumnStretch(0, 1)
        self.grid_db_send.setColumnStretch(1, 1)
        self.verticalLayout_9.addLayout(self.grid_db_send)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_add_send = QtWidgets.QPushButton(self.scroll_widget_send)
        self.b_add_send.setMaximumSize(QtCore.QSize(50, 16777215))
        self.b_add_send.setObjectName("b_add_send")
        self.horizontalLayout.addWidget(self.b_add_send)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.scroll_send.setWidget(self.scroll_widget_send)
        self.verticalLayout_7.addWidget(self.scroll_send)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(4, 1)
        self.mainTabWidget.addTab(self.sql_tab, "")
        self.verticalLayout.addWidget(self.mainTabWidget)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_wait_after_switchbox = QtWidgets.QLabel(self.centralwidget)
        self.label_wait_after_switchbox.setObjectName("label_wait_after_switchbox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_wait_after_switchbox)
        self.doubleSpinBox_wait_after_switchbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_wait_after_switchbox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_wait_after_switchbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_wait_after_switchbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_wait_after_switchbox.setKeyboardTracking(False)
        self.doubleSpinBox_wait_after_switchbox.setMaximum(10.0)
        self.doubleSpinBox_wait_after_switchbox.setObjectName("doubleSpinBox_wait_after_switchbox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_wait_after_switchbox)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_timeout_pre_scan_s = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_timeout_pre_scan_s.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_timeout_pre_scan_s.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_timeout_pre_scan_s.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_timeout_pre_scan_s.setKeyboardTracking(False)
        self.doubleSpinBox_timeout_pre_scan_s.setMaximum(500.0)
        self.doubleSpinBox_timeout_pre_scan_s.setObjectName("doubleSpinBox_timeout_pre_scan_s")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_timeout_pre_scan_s)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        PreScanMainWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(PreScanMainWin)
        self.mainTabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PreScanMainWin)

    def retranslateUi(self, PreScanMainWin):
        _translate = QtCore.QCoreApplication.translate
        PreScanMainWin.setWindowTitle(_translate("PreScanMainWin", "MainWindow"))
        self.checkBox_voltage_measure.setText(_translate("PreScanMainWin", "measure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("PreScanMainWin", "Tab 1"))
        self.label_measVoltPulseLength_mu_s.setText(_translate("PreScanMainWin", "Pulse length for voltage measurement request / <span>&mu;s</span>"))
        self.label_measVoltTimeout_mu_s.setText(_translate("PreScanMainWin", "timeout for voltage measurement / ms"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.volt_tab), _translate("PreScanMainWin", "voltage meas."))
        self.checkBox_triton_measure.setText(_translate("PreScanMainWin", "measure"))
        self.label.setText(_translate("PreScanMainWin", "devices"))
        self.label_channels.setText(_translate("PreScanMainWin", "channels"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.triton_tab), _translate("PreScanMainWin", "triton"))
        self.check_sql_measure.setText(_translate("PreScanMainWin", "measure"))
        self.label_db_measure.setText(_translate("PreScanMainWin", "Database"))
        self.b_add_measure.setText(_translate("PreScanMainWin", "+"))
        self.check_sql_send.setText(_translate("PreScanMainWin", "send run info"))
        self.label_db_send.setText(_translate("PreScanMainWin", "Database"))
        self.b_add_send.setText(_translate("PreScanMainWin", "+"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.sql_tab), _translate("PreScanMainWin", "SQL"))
        self.label_wait_after_switchbox.setText(_translate("PreScanMainWin", "wait after switchbox changed / s"))
        self.label_2.setText(_translate("PreScanMainWin", "timeout for pre scan measurement / s:"))
