# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Users\Patrick\Documents\Python Projects\Tilda\Tilda\Interface\DopplerConfigUi\Ui_DopplerConfig.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DopplerConfig(object):
    def setupUi(self, DopplerConfig):
        DopplerConfig.setObjectName("DopplerConfig")
        DopplerConfig.resize(450, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DopplerConfig.sizePolicy().hasHeightForWidth())
        DopplerConfig.setSizePolicy(sizePolicy)
        DopplerConfig.setMinimumSize(QtCore.QSize(0, 200))
        DopplerConfig.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Europe))
        self.verticalLayout = QtWidgets.QVBoxLayout(DopplerConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hor_mass = QtWidgets.QHBoxLayout()
        self.hor_mass.setObjectName("hor_mass")
        self.label_mass = QtWidgets.QLabel(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mass.sizePolicy().hasHeightForWidth())
        self.label_mass.setSizePolicy(sizePolicy)
        self.label_mass.setObjectName("label_mass")
        self.hor_mass.addWidget(self.label_mass)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_mass.addItem(spacerItem)
        self.d_mass = QtWidgets.QDoubleSpinBox(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_mass.sizePolicy().hasHeightForWidth())
        self.d_mass.setSizePolicy(sizePolicy)
        self.d_mass.setMinimumSize(QtCore.QSize(100, 0))
        self.d_mass.setMaximumSize(QtCore.QSize(100, 16777215))
        self.d_mass.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.d_mass.setDecimals(6)
        self.d_mass.setMinimum(1.0)
        self.d_mass.setMaximum(1000.0)
        self.d_mass.setProperty("value", 40.0)
        self.d_mass.setObjectName("d_mass")
        self.hor_mass.addWidget(self.d_mass)
        self.verticalLayout.addLayout(self.hor_mass)
        self.hor_charge = QtWidgets.QHBoxLayout()
        self.hor_charge.setObjectName("hor_charge")
        self.label_charge = QtWidgets.QLabel(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_charge.sizePolicy().hasHeightForWidth())
        self.label_charge.setSizePolicy(sizePolicy)
        self.label_charge.setObjectName("label_charge")
        self.hor_charge.addWidget(self.label_charge)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_charge.addItem(spacerItem1)
        self.s_charge = QtWidgets.QSpinBox(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_charge.sizePolicy().hasHeightForWidth())
        self.s_charge.setSizePolicy(sizePolicy)
        self.s_charge.setMinimumSize(QtCore.QSize(100, 0))
        self.s_charge.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s_charge.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.s_charge.setMinimum(1)
        self.s_charge.setMaximum(137)
        self.s_charge.setObjectName("s_charge")
        self.hor_charge.addWidget(self.s_charge)
        self.verticalLayout.addLayout(self.hor_charge)
        self.hor_laser_frequency = QtWidgets.QHBoxLayout()
        self.hor_laser_frequency.setObjectName("hor_laser_frequency")
        self.label_laser_frequency = QtWidgets.QLabel(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_laser_frequency.sizePolicy().hasHeightForWidth())
        self.label_laser_frequency.setSizePolicy(sizePolicy)
        self.label_laser_frequency.setObjectName("label_laser_frequency")
        self.hor_laser_frequency.addWidget(self.label_laser_frequency)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_laser_frequency.addItem(spacerItem2)
        self.check_col = QtWidgets.QCheckBox(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_col.sizePolicy().hasHeightForWidth())
        self.check_col.setSizePolicy(sizePolicy)
        self.check_col.setMinimumSize(QtCore.QSize(40, 0))
        self.check_col.setMaximumSize(QtCore.QSize(50, 16777215))
        self.check_col.setChecked(True)
        self.check_col.setObjectName("check_col")
        self.hor_laser_frequency.addWidget(self.check_col)
        self.d_laser_frequency = QtWidgets.QDoubleSpinBox(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_laser_frequency.sizePolicy().hasHeightForWidth())
        self.d_laser_frequency.setSizePolicy(sizePolicy)
        self.d_laser_frequency.setMinimumSize(QtCore.QSize(116, 0))
        self.d_laser_frequency.setMaximumSize(QtCore.QSize(116, 16777215))
        self.d_laser_frequency.setReadOnly(True)
        self.d_laser_frequency.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.d_laser_frequency.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.d_laser_frequency.setDecimals(1)
        self.d_laser_frequency.setMinimum(0.0)
        self.d_laser_frequency.setMaximum(10000000000.0)
        self.d_laser_frequency.setProperty("value", 1.0)
        self.d_laser_frequency.setObjectName("d_laser_frequency")
        self.hor_laser_frequency.addWidget(self.d_laser_frequency)
        self.b_config_frequency = QtWidgets.QPushButton(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_config_frequency.sizePolicy().hasHeightForWidth())
        self.b_config_frequency.setSizePolicy(sizePolicy)
        self.b_config_frequency.setMinimumSize(QtCore.QSize(100, 0))
        self.b_config_frequency.setMaximumSize(QtCore.QSize(100, 16777215))
        self.b_config_frequency.setObjectName("b_config_frequency")
        self.hor_laser_frequency.addWidget(self.b_config_frequency)
        self.hor_laser_frequency.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hor_laser_frequency)
        self.hor_voltage = QtWidgets.QHBoxLayout()
        self.hor_voltage.setObjectName("hor_voltage")
        self.label_voltage = QtWidgets.QLabel(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_voltage.sizePolicy().hasHeightForWidth())
        self.label_voltage.setSizePolicy(sizePolicy)
        self.label_voltage.setObjectName("label_voltage")
        self.hor_voltage.addWidget(self.label_voltage)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_voltage.addItem(spacerItem3)
        self.d_voltage = QtWidgets.QDoubleSpinBox(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_voltage.sizePolicy().hasHeightForWidth())
        self.d_voltage.setSizePolicy(sizePolicy)
        self.d_voltage.setMinimumSize(QtCore.QSize(116, 0))
        self.d_voltage.setMaximumSize(QtCore.QSize(116, 16777215))
        self.d_voltage.setReadOnly(True)
        self.d_voltage.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.d_voltage.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.d_voltage.setDecimals(6)
        self.d_voltage.setMaximum(10000000.0)
        self.d_voltage.setProperty("value", 20000.0)
        self.d_voltage.setObjectName("d_voltage")
        self.hor_voltage.addWidget(self.d_voltage)
        self.b_config_voltage = QtWidgets.QPushButton(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_config_voltage.sizePolicy().hasHeightForWidth())
        self.b_config_voltage.setSizePolicy(sizePolicy)
        self.b_config_voltage.setMinimumSize(QtCore.QSize(100, 0))
        self.b_config_voltage.setMaximumSize(QtCore.QSize(100, 16777215))
        self.b_config_voltage.setObjectName("b_config_voltage")
        self.hor_voltage.addWidget(self.b_config_voltage)
        self.hor_voltage.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hor_voltage)
        self.hor_amplifier = QtWidgets.QHBoxLayout()
        self.hor_amplifier.setObjectName("hor_amplifier")
        self.label_amplifier = QtWidgets.QLabel(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_amplifier.sizePolicy().hasHeightForWidth())
        self.label_amplifier.setSizePolicy(sizePolicy)
        self.label_amplifier.setObjectName("label_amplifier")
        self.hor_amplifier.addWidget(self.label_amplifier)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_amplifier.addItem(spacerItem4)
        self.d_slope = QtWidgets.QDoubleSpinBox(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_slope.sizePolicy().hasHeightForWidth())
        self.d_slope.setSizePolicy(sizePolicy)
        self.d_slope.setMinimumSize(QtCore.QSize(64, 0))
        self.d_slope.setMaximumSize(QtCore.QSize(64, 16777215))
        self.d_slope.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.d_slope.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.d_slope.setDecimals(3)
        self.d_slope.setMinimum(1.0)
        self.d_slope.setMaximum(100000.0)
        self.d_slope.setProperty("value", 50.0)
        self.d_slope.setObjectName("d_slope")
        self.hor_amplifier.addWidget(self.d_slope)
        self.label_times_amp = QtWidgets.QLabel(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_times_amp.sizePolicy().hasHeightForWidth())
        self.label_times_amp.setSizePolicy(sizePolicy)
        self.label_times_amp.setMinimumSize(QtCore.QSize(20, 0))
        self.label_times_amp.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_times_amp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_times_amp.setObjectName("label_times_amp")
        self.hor_amplifier.addWidget(self.label_times_amp)
        self.label_plus = QtWidgets.QLabel(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_plus.sizePolicy().hasHeightForWidth())
        self.label_plus.setSizePolicy(sizePolicy)
        self.label_plus.setMinimumSize(QtCore.QSize(20, 0))
        self.label_plus.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_plus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_plus.setObjectName("label_plus")
        self.hor_amplifier.addWidget(self.label_plus)
        self.d_offset = QtWidgets.QDoubleSpinBox(DopplerConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_offset.sizePolicy().hasHeightForWidth())
        self.d_offset.setSizePolicy(sizePolicy)
        self.d_offset.setMinimumSize(QtCore.QSize(100, 0))
        self.d_offset.setMaximumSize(QtCore.QSize(100, 16777215))
        self.d_offset.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.d_offset.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.d_offset.setDecimals(3)
        self.d_offset.setMaximum(100000.0)
        self.d_offset.setObjectName("d_offset")
        self.hor_amplifier.addWidget(self.d_offset)
        self.hor_amplifier.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hor_amplifier)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.hor_buttons = QtWidgets.QHBoxLayout()
        self.hor_buttons.setObjectName("hor_buttons")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hor_buttons.addItem(spacerItem6)
        self.b_ok = QtWidgets.QPushButton(DopplerConfig)
        self.b_ok.setObjectName("b_ok")
        self.hor_buttons.addWidget(self.b_ok)
        self.b_cancel = QtWidgets.QPushButton(DopplerConfig)
        self.b_cancel.setObjectName("b_cancel")
        self.hor_buttons.addWidget(self.b_cancel)
        self.verticalLayout.addLayout(self.hor_buttons)

        self.retranslateUi(DopplerConfig)
        QtCore.QMetaObject.connectSlotsByName(DopplerConfig)

    def retranslateUi(self, DopplerConfig):
        _translate = QtCore.QCoreApplication.translate
        DopplerConfig.setWindowTitle(_translate("DopplerConfig", "Doppler Config"))
        self.label_mass.setText(_translate("DopplerConfig", "Mass (u)"))
        self.d_mass.setSuffix(_translate("DopplerConfig", " u"))
        self.label_charge.setText(_translate("DopplerConfig", "Charge (e)"))
        self.s_charge.setSuffix(_translate("DopplerConfig", " e"))
        self.label_laser_frequency.setText(_translate("DopplerConfig", "Laser frequency (MHz)"))
        self.check_col.setText(_translate("DopplerConfig", "col"))
        self.d_laser_frequency.setSuffix(_translate("DopplerConfig", " MHz"))
        self.b_config_frequency.setText(_translate("DopplerConfig", "config ..."))
        self.label_voltage.setText(_translate("DopplerConfig", "Acceleration voltage (V)"))
        self.d_voltage.setSuffix(_translate("DopplerConfig", " V"))
        self.b_config_voltage.setText(_translate("DopplerConfig", "config ..."))
        self.label_amplifier.setText(_translate("DopplerConfig", "Amplifier (V)"))
        self.label_times_amp.setText(_translate("DopplerConfig", "<nobr>&times; <i>U</i></nobr>"))
        self.label_plus.setText(_translate("DopplerConfig", "+"))
        self.d_offset.setSuffix(_translate("DopplerConfig", " V"))
        self.b_ok.setText(_translate("DopplerConfig", "OK"))
        self.b_cancel.setText(_translate("DopplerConfig", "Cancel"))
